---
title: "_Reporting_Params"
author: "Matthew Hamilton & Caroline Gao"
date: "04/06/2021"
output: html_document
---

### Bibliograhic data
We begin by specifying the authorship data we wish to attach to all reports that we generate.

```{r }
authors_tb <- ready4show::authors_tb
```
```{r authorsds, eval = knitr::is_html_output(), echo=F, results='asis'}
authors_tb %>%
  ready4show::print_table(output_type_1L_chr = "HTML",
                          caption_1L_chr = "Authors table",
                          mkdn_tbl_ref_1L_chr = "tab:authorsds")
```
```{r}
institutes_tb <- ready4show::institutes_tb
```
```{r institutesds, eval = knitr::is_html_output(), echo = F,results='asis'}
institutes_tb %>%
  ready4show::print_table(output_type_1L_chr = "HTML",
                          caption_1L_chr = "Author institutions table",
                          mkdn_tbl_ref_1L_chr = "tab:institutesds")
```

We combine the data about authors with other bibliographic information.

```{r}
header_yaml_args_ls <- ready4show::make_header_yaml_args_ls(authors_tb = authors_tb,
                                                     institutes_tb = institutes_tb,
                                                     title_1L_chr = "A hypothetical study using fake data for instructional purposes only",
                                                     keywords_chr = c("this","is","a","replication","using","fake","data","do", "not","cite"))
```

### Report formatting
We add parameters relating to the desired output format of the reports we will be producing.

```{r }
output_format_ls <- TTU::ready4show::make_output_format_ls(manuscript_outp_1L_chr = "Word",
                                               manuscript_digits_1L_int = 2L,
                                               supplementary_outp_1L_chr = "PDF",
                                               supplementary_digits_1L_int = 2L)
```
