library(magrittr)
ready4fun::read_fns("data-raw/fns")
source("data-raw/MAKE_CLASSES.R")
abbreviations_lup <- ready4fun::get_rds_from_dv("abbreviations_lup")
fn_type_lup_tb <- ready4fun::get_rds_from_dv("fn_type_lup_tb")
# Edits go here
abbreviations_lup <- abbreviations_lup %>%
  ready4fun::update_abbr_lup(short_name_chr = c("auto",
                                                "brm",
                                                "clg",
                                                "cll",
                                                "ctg",
                                                "cndt",
                                                "dnst",
                                                "elmt",
                                                "fctr",
                                                "grp",
                                                "gsn",
                                                "itm",
                                                "lm",
                                                "lnr",
                                                "mdlng",
                                                "msng",
                                                "obsd",
                                                "pdef",
                                                "plt",
                                                "prefd",
                                                "popl",
                                                "predd",
                                                "prob",
                                                "prpn",
                                                "rmse",
                                                "rsl",
                                                "sclg",
                                                "sctr",
                                                "signft",
                                                "sngl",
                                                "synth",
                                                "temp",
                                                "tmpl",
                                                "tstng",
                                                "vec",
                                                "wrst"),
                             long_name_chr = c("automatic",
                                               "bayesian regression model",
                                               "complementary log",
                                               "complementary log log",
                                               "category categories",
                                               "candidate",
                                               "density",
                                               "element",
                                               "factor",
                                               "group",
                                               "gaussian",
                                               "item",
                                               "linear model",
                                               "linear",
                                               "modelling",
                                               "missing",
                                               "observed",
                                               "positive definite",
                                               "plot", # check if in object_lup
                                               "preferred",
                                               "population",
                                               "predicted",
                                               "probability",
                                               "proportion",
                                               "root mean square error",
                                               "resolution",
                                               "scaling",
                                               "scatter",
                                               "significant",
                                               "single",
                                               "synthetic",
                                               "temporary",
                                               "template",
                                               "testing",
                                               "vector",
                                               "worst"),
                             no_plural_chr = c("gaussian","modelling","missing","observed","positive definite",
                                               "preferred","population"," predicted","significant","temporary",
                                               "testing","worst"),
                             custom_plural_ls = list(category = "categories",
                                                     probability = "probabilities"))
# Push updates to dataverse
abbreviations_lup %>%
  ready4use::write_paired_ds_fls_to_dv(fl_nm_1L_chr = "abbreviations_lup",
                            desc_1L_chr = "Abbreviations lookup table")
fn_type_lup_tb %>%
  ready4use::write_paired_ds_fls_to_dv(fl_nm_1L_chr = "fn_type_lup_tb",
                            desc_1L_chr = "Function type lookup table")
# NOTE: Don't forget to review and publish the updated dataset.
# Previous edits
# abbreviations_lup <- abbreviations_lup %>%
#   ready4fun::update_abbr_lup(short_name_chr = c("cnstr","con","cor",
#                                                 "lgd",
#                                                 #"mdl",
#                                                 "predn",
#                                                 "tfmn",
#                                                 "tot",
#                                                 "ts",
#                                                 "uid",
#                                                 "ut"),
#                              long_name_chr = c("constraint",
#                                                "constant",
#                                                "correlation",
#                                                "legend",
#                                                #"model",
#                                                "prediction",
#                                                "transformation",
#                                                "total",
#                                                "time series",
#                                                "unique identifier",
#                                                "utility"),
#                              no_plural_chr = c("prediction","time series"),
#                              custom_plural_ls = list(utility = "utilities"))
# abbreviations_lup <- abbreviations_lup %>%
#   ready4fun::update_abbr_lup(short_name_chr = c(paste0(name_pfx_1L_chr,classes_to_make_tb$name_stub_chr)),
#                              long_name_chr = c(classes_to_make_tb$class_desc_chr),
#                              no_plural_chr = NA_character_,
#                              custom_plural_ls = NULL, pfx_rgx = NA_character_)
# abbreviations_lup <- abbreviations_lup %>%
#   dplyr::mutate(short_name_chr = dplyr::case_when(short_name_chr == "ut" ~ "utl",
#                                                   short_name_chr == "uts" ~ "utls",
#                                                   T ~ short_name_chr))
# abbreviations_lup <- abbreviations_lup %>%
#   ready4fun::update_abbr_lup(short_name_chr = c("adol6d",
#                                                 "bl",
#                                                 "bnml",
#                                                 "cmprsn",
#                                                 "coef",
#                                                 "covar",
#                                                 "dict",
#                                                 "id",
#                                                 "iter",
#                                                 "min",
#                                                 "max",
#                                                 "mdl",
#                                                 "msrmnt",
#                                                 "nbr",
#                                                 "predr",
#                                                 "repln",
#                                                 "rltv",
#                                                 "rmd",
#                                                 "rmv",
#                                                 "smry",
#                                                 "tfmd",
#                                                 "var",
#                                                 "wt",
#                                                 "wtd"),
#                              long_name_chr = c("Assessment of Quality of Life Six Dimension",
#                                                "baseline",
#                                                "binomial",
#                                                "comparison",
#                                                "coefficient",
#                                                "covariate",
#                                                "dictionary",
#                                                "identity",
#                                                "iteration",
#                                                "minimum",
#                                                "maximum",
#                                                "model",
#                                                "measurement",
#                                                "number",
#                                                "predictor",
#                                                "replication",
#                                                "relative",
#                                                "R Markdown",
#                                                "remove",
#                                                "summary",
#                                                "transformed",
#                                                "variable",
#                                                "weight",
#                                                "weighted"),
#                              no_plural_chr = c("transformed","weighted"),
#                              custom_plural_ls = list(dictionary = "dictionaries",
#                                                      identity = "identities"))
# abbreviations_lup <- abbreviations_lup %>%
#   dplyr::filter(short_name_chr != "tfmd") %>%
#   dplyr::mutate(long_name_chr = dplyr::case_when(short_name_chr == "adol6d" ~ "Assessment of Quality of Life Six Dimension (Adolescent version)",
#                                                  T ~ long_name_chr))
# abbreviations_lup <- abbreviations_lup %>%
#   dplyr::filter(short_name_chr != "adol6ds") %>%
#   dplyr::mutate(plural_lgl = dplyr::case_when(short_name_chr == "adol6d" ~ NA,
#                                               T ~ plural_lgl))
# abbreviations_lup <- abbreviations_lup %>%
#   dplyr::filter(!short_name_chr %in% c(paste0(name_pfx_1L_chr,classes_to_make_tb$name_stub_chr))) %>%
#   dplyr::filter(!short_name_chr %in% c(paste0(paste0(name_pfx_1L_chr,classes_to_make_tb$name_stub_chr),"s"))) %>%
#   ready4fun::update_abbr_lup(short_name_chr = c(paste0(name_pfx_1L_chr,classes_to_make_tb$name_stub_chr)),
#                              long_name_chr = c(classes_to_make_tb$class_desc_chr),
#                              no_plural_chr = c(classes_to_make_tb$class_desc_chr),
#                              custom_plural_ls = NULL, pfx_rgx = NA_character_)
# fn_type_lup_tb <- fn_type_lup_tb %>%
#   ready4fun::add_rows_to_fn_type_lup(fn_type_nm_chr = ready4fun::get_new_fn_types(abbreviations_lup = abbreviations_lup,
#                                                                                   fn_type_lup_tb = fn_type_lup_tb),
#                                      fn_type_desc_chr = c("Fits a model of a specified type to a dataset",
#                                                           "Knits a rmarkdown file",
#                                                           "Plots data",
#                                                           "Makes predictions from data using a specified statistical model.",
#                                                           "Randomly samples from data.",
#                                                           "Reorders an object to conform to a pre-specified schema.",
#                                                           "Randomly reorders an object."
#                                      ),
#                                      is_generic_lgl = F,
#                                      is_method_lgl = F)

