## ready4fun::write_new_obj_types(x_xx$x_ready4fun_manifest, long_name_chr = "New dataset (for prediction)") -> x_xx$x_ready4fun_manifest
# x_xx$x_ready4fun_manifest <- ready4::renew(x_xx$x_ready4fun_manifest,
#                                            are_words_chr = c("backend", "betareg",
#                                                              "boruta", "covariates",
#                                                              "deterministic", "multi",
#                                                              "shareable", "timepoint",
#                                                              "ungroup","yhat"),
#                                            type_1L_chr = "words")
x_xx$x_ready4fun_manifest <- ready4::renew(x_xx$x_ready4fun_manifest,
                                           long_name_chr = c("analysis",#es
                                                             "regression model intercept",
                                                             "regression model coefficient",
                                                             "between",
                                                             "composite",
                                                             "conflict of interest",
                                                             "cross-section",
                                                             "cross-sectional",
                                                             "complete study program",
                                                             "categorical",
                                                             "digital object identifier",
                                                             "EQ5D",
                                                             "family",
                                                             "generalised linear model",
                                                             "independent",
                                                             "K10",
                                                             "longitudinal",
                                                             "mixed",
                                                             "number of columns",
                                                             "ordinary least squares",
                                                             "predict",
                                                             "primary",
                                                             "R squared",
                                                             "record",
                                                             "secondary",
                                                             "standard error",
                                                             "shareable",
                                                             "supplementary",
                                                             "transfer to utility algorithm",
                                                             "unconstrained"),
                                           custom_plural_ls = list(analysis = "analyses",
                                                                   family = "families",
                                                                   primary = "primaries",
                                                                   secondary = "secondaries",
                                                                   supplementary = "supplementaries"),
                                           no_plural_chr = c("between",
                                                             "cross-sectional",
                                                             "EQ5D",
                                                             "K10",
                                                             "longitudinal",
                                                             "mixed",
                                                             "number of columns",
                                                             "ordinary least squares",
                                                             "unconstrained"),
                                           type_1L_chr = "abbreviations")
##
# dv_ls <- list(primary_dv_chr = c("fakes","https://doi.org/10.7910/DVN/612HDC"))
# fake_eq5d_ds_tb <- make_fake_eq5d_ds()
# saveRDS(fake_eq5d_ds_tb,"data-raw/dataverse/fake_eq5d_ds_tb.Rds")
# ready4::write_to_dv_with_wait(dss_tb = tibble::tibble(ds_obj_nm_chr = "fake_eq5d_ds_tb",
#                                                       title_chr = "A synthetic (entirely fake) dataset with psychological distress, psychological wellbeing and EQ5D questionaire response variables."),
#                               dv_nm_1L_chr = dv_ls$primary_dv_chr[1],
#                               ds_url_1L_chr = dv_ls$primary_dv_chr[2],
#                               parent_dv_dir_1L_chr = "data-raw/dataverse",
#                               paths_to_dirs_chr = "data-raw/dataverse",
#                               inc_fl_types_chr = ".RDS",
#                               paths_are_rltv_1L_lgl = T)
##
## Add, Commit and Push
# system("git add .")
# system("git commit -m \"message\"")
