---
title: "Linear Model"
author: "Caroline Gao"
date: "13/08/2020"
output: html_document
---


## Linear model (no transformation)


```{r}
summary_table <- data.frame("Model"=NA,"Rsquare"=NA,"RMSE"=NA, "MAE"=NA, "Rsquare.prediction"=NA, "RMSE prediction"=NA,"MAE prediction"=NA)

#library(ggfortify)
fit = lm(aqol6d_total_w ~ PHQ9, data = baseline)
summary(fit)

newdata <- data.frame(PHQ9=0:27)
newdata$aqol6d_total_w=predict(fit,newdata=newdata)
 
ggplot2::ggplot(baseline,ggplot2::aes(x = PHQ9, y= aqol6d_total_w )) +
  ggplot2::geom_point() + 
  ggplot2::geom_smooth(method = "loess", size = 1.5) +
  ggplot2::geom_line(data=newdata,ggplot2::aes(x = PHQ9, y= aqol6d_total_w),col="red")  +
  ggplot2::theme_bw() + ggplot2::labs(x="PHQ9 total score",y="AQoL-6D utility score")

ggplot2::autoplot(fit, which = 1:6, ncol = 3, label.size = 3)


baseline %>% 
    dplyr::mutate(Predicted=predict(fit),
         Original=aqol6d_total_w) %>% 
    tidyr::gather(variable, value, Predicted, Original) %>%
    ggplot2::ggplot(ggplot2::aes(x = value, fill = variable)) +
    ggalt::geom_bkde(alpha=0.5) +
    ggplot2::geom_rug() +
    viridis::scale_fill_viridis( discrete = TRUE) +
    ggplot2::theme_bw() +
    ggplot2::theme(legend.position="bottom") +
    ggplot2::labs(x="AQoL-6D utility score",fill="")

baseline %>% 
    dplyr::mutate(Simulated=simulate(fit)$sim_1, 
         Original=aqol6d_total_w) %>% 
    tidyr::gather(variable, value, Simulated, Original) %>%
    ggplot2::ggplot(ggplot2::aes(x = value, fill = variable)) +
    ggalt::geom_bkde(alpha=0.5) +
    ggplot2::geom_rug() +
    viridis::scale_fill_viridis( discrete = TRUE) +
    ggplot2::theme_bw() +
    ggplot2::theme(legend.position="bottom") +
    ggplot2::labs( x="AQoL-6D utility score",fill="")

baseline %>% 
  dplyr::mutate(Predicted=predict(fit),
         Original=aqol6d_total_w) %>% 
  ggplot2::ggplot(ggplot2::aes(x = Original, y=Predicted)) +
  ggplot2::geom_point() + 
  ggplot2::geom_smooth(method = "loess", size = 1.5) +
  ggplot2::theme_bw() +
  ggplot2::geom_abline(intercept = 0, slope = 1, color="red", 
                 linetype="dashed", size=1.5) +
  ggplot2::xlim(0, 1) + ggplot2::ylim(0, 1)


Rsquared<-NA
RMSE<-NA
MAE<-NA
RsquaredP<-NA
RMSEP<-NA
MAEP<-NA
for (i in 1:10) {
  fit = lm(aqol6d_total_w ~ PHQ9, data = baseline[-folds_10[[i]],])
  pred<-predict(fit)
  Rsquared[i]=caret::R2(pred, baseline[-folds_10[[i]],]$aqol6d_total_w, form = "traditional")
  RMSE[i]=caret::RMSE(pred, baseline[-folds_10[[i]],]$aqol6d_total_w)
  MAE[i]=caret::MAE(pred, baseline[-folds_10[[i]],]$aqol6d_total_w)
  pred<-predict(fit,newdata=baseline[folds_10[[i]],])
  RsquaredP[i]=caret::R2(pred, baseline[folds_10[[i]],]$aqol6d_total_w, form = "traditional")
  RMSEP[i]=caret::RMSE(pred, baseline[folds_10[[i]],]$aqol6d_total_w)
  MAEP[i]=caret::MAE(pred, baseline[folds_10[[i]],]$aqol6d_total_w)
} 

n=1
#save model fit
summary_table[n,1]="OLS (no transformation)" 
summary_table$Rsquare[n]= mean(Rsquared)
summary_table$RMSE[n]= mean(RMSE)
summary_table$MAE[n]=mean(MAE)
summary_table$`Rsquare.prediction`[n]=mean(RsquaredP)
summary_table$`RMSE.prediction`[n]=mean(RMSEP)
summary_table$`MAE.prediction`[n]=mean(MAEP)

```



## Linear model (log transformation)

```{r}

fit = lm(aqol6d_total_w_log ~ PHQ9, data = baseline)
summary(fit)

newdata<-data.frame(PHQ9=0:27)
newdata$aqol6d_total_w=exp(predict(fit,newdata=newdata))
 
ggplot2::ggplot(baseline,ggplot2::aes(x = PHQ9, y= aqol6d_total_w )) +
  ggplot2::geom_point() + 
  ggplot2::geom_smooth(method = "loess", size = 1.5) +
  ggplot2::geom_line(data=newdata,aes(x = PHQ9, y= aqol6d_total_w),col="red")  +
  ggplot2::theme_bw() + ggplot2::labs(x="PHQ9 total score",y="AQoL-6D utility score")

ggplot2::autoplot(fit, which = 1:6, ncol = 3, label.size = 3)

baseline %>% 
    dplyr::mutate(Predicted=exp(predict(fit)),
         Original=aqol6d_total_w) %>% 
    tidyr::gather(variable, value, Predicted, Original) %>%
    ggplot2::ggplot(aes(x = value, fill = variable)) +
    ggalt::geom_bkde(alpha=0.5) +
    ggplot2::geom_rug() +
    viridis::scale_fill_viridis( discrete = TRUE) +
    ggplot2::theme_bw() +
    ggplot2::theme(legend.position="bottom") +
    ggplot2::labs( x="AQoL-6D utility score",fill="")


baseline %>% 
    dplyr::mutate(Simulated=exp(simulate(fit)$sim_1),
         Original=aqol6d_total_w) %>% 
    tidyr::gather(variable, value, Simulated, Original) %>%
    ggplot2::ggplot(aes(x = value, fill = variable)) +
    ggalt::geom_bkde(alpha=0.5) +
    ggplot2::geom_rug() +
    viridis::scale_fill_viridis( discrete = TRUE) +
    ggplot2::theme_bw() +
    ggplot2::theme(legend.position="bottom") +
    ggplot2::labs( x="AQoL-6D utility score",fill="")


baseline %>% 
    dplyr::mutate(Predicted=exp(predict(fit)),
         Original=aqol6d_total_w) %>% 
  ggplot2::ggplot(aes(x = Original, y=Predicted)) +
  ggplot2::geom_point() + 
  ggplot2::geom_smooth(method = "loess", size = 1.5) +
  ggplot2::theme_bw() +
  ggplot2::geom_abline(intercept = 0, slope = 1, color="red", 
                 linetype="dashed", size=1.5) +
  xlim(0, 1) + ylim(0, 1)

Rsquared<-NA
RMSE<-NA
MAE<-NA
RsquaredP<-NA
RMSEP<-NA
MAEP<-NA
for (i in 1:10) {
  fit = lm(aqol6d_total_w_log ~ PHQ9, data = baseline[-folds_10[[i]],])
  pred<-exp(predict(fit))
  Rsquared[i]=caret::R2(pred, baseline[-folds_10[[i]],]$aqol6d_total_w, form = "traditional")
  RMSE[i]=caret::RMSE(pred, baseline[-folds_10[[i]],]$aqol6d_total_w)
  MAE[i]=caret::MAE(pred, baseline[-folds_10[[i]],]$aqol6d_total_w)
  pred<-exp(predict(fit,newdata=baseline[folds_10[[i]],]))
  RsquaredP[i]=caret::R2(pred, baseline[folds_10[[i]],]$aqol6d_total_w, form = "traditional")
  RMSEP[i]=caret::RMSE(pred, baseline[folds_10[[i]],]$aqol6d_total_w)
  MAEP[i]=caret::MAE(pred, baseline[folds_10[[i]],]$aqol6d_total_w)
} 

n=n+1
#save model fit
summary_table[n,1]="OLS (log)" 
summary_table$Rsquare[n]= mean(Rsquared)
summary_table$RMSE[n]= mean(RMSE)
summary_table$MAE[n]=mean(MAE)
summary_table$`Rsquare.prediction`[n]=mean(RsquaredP)
summary_table$`RMSE.prediction`[n]=mean(RMSEP)
summary_table$`MAE.prediction`[n]=mean(MAEP)
``` 



## Linear model (logit transformation)

```{r}
library(boot)
fit = lm(aqol6d_total_w_logit ~ PHQ9, data = baseline)
summary(fit)

newdata <- data.frame(PHQ9=0:27)
newdata$aqol6d_total_w=inv.logit(predict(fit,newdata=newdata))
 
ggplot2::ggplot(baseline,aes(x = PHQ9, y= aqol6d_total_w )) +
  ggplot2::geom_point() + 
  ggplot2::geom_smooth(method = "loess", size = 1.5) +
  ggplot2::geom_line(data=newdata,aes(x = PHQ9, y= aqol6d_total_w),col="red")  +
  ggplot2::theme_bw() + labs(x="PHQ9 total score",y="AQoL-6D utility score")

ggplot2::autoplot(fit, which = 1:6, ncol = 3, label.size = 3)

 
baseline %>% 
    dplyr::mutate(Predicted=inv.logit(predict(fit)),
         Original=aqol6d_total_w) %>%  
    tidyr::gather(variable, value, Predicted, Original) %>%
    ggplot2::ggplot(aes(x = value, fill = variable)) +
    ggalt::geom_bkde(alpha=0.5) +
    ggplot2::geom_rug() +
    viridis::scale_fill_viridis( discrete = TRUE) +
    ggplot2::theme_bw() +
    ggplot2::theme(legend.position="bottom") +
    ggplot2::labs( x="AQoL-6D utility score",fill="")

baseline %>% 
    dplyr::mutate(Simulated=inv.logit(simulate(fit)$sim_1) ,
         Original=aqol6d_total_w) %>%  
    tidyr::gather(variable, value, Simulated, Original) %>%
    ggplot2::ggplot(aes(x = value, fill = variable)) +
    ggalt::geom_bkde(alpha=0.5) +
    ggplot2::geom_rug() +
    viridis::scale_fill_viridis( discrete = TRUE) +
    ggplot2::theme_bw() +
    ggplot2::theme(legend.position="bottom") +
    ggplot2::labs(x="AQoL-6D utility score",fill="")


baseline %>% 
    dplyr::mutate(Predicted=inv.logit(predict(fit)),
         Original=aqol6d_total_w) %>% 
  ggplot2::ggplot(aes(x = Original, y=Predicted)) +
  ggplot2::geom_point() + 
  ggplot2::geom_smooth(method = "loess", size = 1.5) +
  ggplot2::theme_bw() +
  ggplot2::geom_abline(intercept = 0, slope = 1, color="red", 
                 linetype="dashed", size=1.5) +
  xlim(0, 1) + ylim(0, 1)

Rsquared<-NA
RMSE<-NA
MAE<-NA
RsquaredP<-NA
RMSEP<-NA
MAEP<-NA
for (i in 1:10) {
  fit = lm(aqol6d_total_w_logit ~ PHQ9, data = baseline[-folds_10[[i]],])
  pred<-inv.logit(predict(fit))
  Rsquared[i]=caret::R2(pred, baseline[-folds_10[[i]],]$aqol6d_total_w, form = "traditional")
  RMSE[i]=caret::RMSE(pred, baseline[-folds_10[[i]],]$aqol6d_total_w)
  MAE[i]=caret::MAE(pred, baseline[-folds_10[[i]],]$aqol6d_total_w)
  pred<-inv.logit(predict(fit,newdata=baseline[folds_10[[i]],]))
  RsquaredP[i]=caret::R2(pred, baseline[folds_10[[i]],]$aqol6d_total_w, form = "traditional")
  RMSEP[i]=caret::RMSE(pred, baseline[folds_10[[i]],]$aqol6d_total_w)
  MAEP[i]=caret::MAE(pred, baseline[folds_10[[i]],]$aqol6d_total_w)
} 

n=n+1
#save model fit
summary_table[n,1]="OLS (logit)" 
summary_table$Rsquare[n]= mean(Rsquared)
summary_table$RMSE[n]= mean(RMSE)
summary_table$MAE[n]=mean(MAE)
summary_table$`Rsquare.prediction`[n]=mean(RsquaredP)
summary_table$`RMSE.prediction`[n]=mean(RMSEP)
summary_table$`MAE.prediction`[n]=mean(MAEP)
``` 




## Linear model (log-log transformation)

```{r}
library(ggfortify)
fit = lm(aqol6d_total_w_loglog ~ PHQ9, data = baseline)
summary(fit)

newdata<-data.frame(PHQ9=0:27)
newdata$aqol6d_total_w=exp(-exp(-predict(fit,newdata=newdata)))
 
ggplot(baseline,aes(x = PHQ9, y= aqol6d_total_w )) +
  geom_point() + 
  geom_smooth(method = "loess", size = 1.5) +
  geom_line(data=newdata,aes(x = PHQ9, y= aqol6d_total_w),col="red")  +
  theme_bw() + labs(x="PHQ9 total score",y="AQoL-6D utility score")


ggplot2::autoplot(fit, which = 1:6, ncol = 3, label.size = 3)


 
baseline %>% 
    dplyr::mutate(Predicted=exp(-exp(-predict(fit))) ,
         Original=aqol6d_total_w) %>%  
    tidyr::gather(variable, value, Predicted, Original) %>%
    ggplot2::ggplot(aes(x = value, fill = variable)) +
    ggalt::geom_bkde(alpha=0.5) +
    ggplot2::geom_rug() +
    viridis::scale_fill_viridis( discrete = TRUE) +
    ggplot2::theme_bw() +
    ggplot2::theme(legend.position="bottom") +
    ggplot2::labs( x="AQoL-6D utility score",fill="") 

baseline %>% 
    dplyr::mutate(Simulated=exp(-exp(-simulate(fit)$sim_1)) ,
         Original=aqol6d_total_w) %>%  
    tidyr::gather(variable, value, Simulated, Original) %>%
    ggplot2::ggplot(aes(x = value, fill = variable)) +
    ggalt::geom_bkde(alpha=0.5) +
    ggplot2::geom_rug() +
    viridis::scale_fill_viridis( discrete = TRUE) +
    ggplot2::theme_bw() +
    ggplot2::theme(legend.position="bottom") +
    ggplot2::labs( x="AQoL-6D utility score",fill="") 

baseline %>% 
    dplyr::mutate(Predicted=exp(-exp(-predict(fit))) ,
         Original=aqol6d_total_w) %>% 
  ggplot2::ggplot(aes(x = Original, y=Predicted)) +
  ggplot2::geom_point() + 
  ggplot2::geom_smooth(method = "loess", size = 1.5) +
  ggplot2::theme_bw() +
  ggplot2::geom_abline(intercept = 0, slope = 1, color="red", 
                 linetype="dashed", size=1.5) +
  xlim(0, 1) + ylim(0, 1) 



Rsquared<-NA 
RMSE<-NA 
MAE<-NA 
RsquaredP<-NA 
RMSEP<-NA 
MAEP<-NA 
for (i in 1:10) {
  fit = lm(aqol6d_total_w_loglog ~ PHQ9, data = baseline[-folds_10[[i]],])
  pred<-exp(-exp(-predict(fit))) 
  Rsquared[i]=caret::R2(pred, baseline[-folds_10[[i]],]$aqol6d_total_w, form = "traditional")
  RMSE[i]=caret::RMSE(pred, baseline[-folds_10[[i]],]$aqol6d_total_w)
  MAE[i]=caret::MAE(pred, baseline[-folds_10[[i]],]$aqol6d_total_w)
  pred<-exp(-exp(-predict(fit,newdata=baseline[folds_10[[i]],]))) 
  RsquaredP[i]=caret::R2(pred, baseline[folds_10[[i]],]$aqol6d_total_w, form = "traditional")
  RMSEP[i]=caret::RMSE(pred, baseline[folds_10[[i]],]$aqol6d_total_w)
  MAEP[i]=caret::MAE(pred, baseline[folds_10[[i]],]$aqol6d_total_w)
} 


n=n+1
#save model fit
summary_table[n,1]="OLS (loglog)" 
summary_table$Rsquare[n]= mean(Rsquared)
summary_table$RMSE[n]= mean(RMSE)
summary_table$MAE[n]=mean(MAE)
summary_table$`Rsquare.prediction`[n]=mean(RsquaredP)
summary_table$`RMSE.prediction`[n]=mean(RMSEP)
summary_table$`MAE.prediction`[n]=mean(MAEP)

``` 

