---
title: "AQol-6D analyses"
author: "Caroline Gao"
output:
  html_document: 
    code_folding: "hide"
    toc: yes 
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(xtable)
library(ready4u)
#devtools::load_all()
```

```{r}
#load libraries 
# library(pacman)
# p_load("dplyr", "tidyr","magrittr","reshape2", "ggplot2","gridExtra", "data.table",  "kableExtra", "knitr",  "here","tidyselect","scales", "ggpubr","Hmisc","stringr","psych","corrplot","arsenal","lavaan","semTools","semPlot","sandwich",
# "ggalt","viridis", "ggthemes", "caret")
# R information 
sessionInfo()

# function for correlation star 


```


# Import the data 

```{r}
aqol6d_tb <- transform_raw_aqol_tb_to_aqol6d_tb(readRDS("../Data/fake_pop_tb.rds"))
nrow(aqol6d_tb)
```

Check missing

```{r}
# non missing 
table(aqol6d_tb[!is.na(aqol6d_tb$aqol6d_total_c),]$round)
nrow(aqol6d_tb)
```

# Descriptive statistics 


```{r, results='asis'}
my_controls <- arsenal::tableby.control(
  test = F,
  total = F,
  digits=1,
  digits.pct=1,
  digits.p=3,
  numeric.test = "anova", cat.test = "chisq",
  numeric.stats = c("meansd", "medianq1q3", "range", "Nmiss2"),
  cat.stats = c("countpct", "Nmiss2"),
  ordered.stats=c("countpct", "Nmiss2"),
  stats.labels = list(
    meansd = "Mean (SD)",
    medianq1q3 = "Median (Q1, Q3)",
    range = "Min - Max",
    Nmiss2 = "Missing"
  )
)
 
table <- arsenal::tableby( round  ~ d_age + d_agegroup + Gender + d_sexual_ori_s + Region + CALD +  d_studying_working  + c_p_diag_s + c_clinical_staging_s + SOFAS ,
  data = aqol6d_tb,
  control = my_controls
)
 
summary(table,
  title = "Participant characteristics"
)
```

# Outcome table
```{r, results='asis'}
 
table <- arsenal::tableby(  round~  PHQ9 +  BADS+ GAD7 +OASIS+ SCARED + K6  + aqol6d_total_c  + aqol6d_total_w ,
  data = aqol6d_tb,
  control = my_controls
)
 
summary(table,
  title = "Participant outcome"
)
```

# Correlation 

```{r, results='asis'}
baseline <- aqol6d_tb %>% 
   dplyr::filter(round=="Baseline") %>% 
   dplyr::select( aqol6d_total_w, PHQ9 ,  BADS, GAD7 ,OASIS,  SCARED, K6,) 

make_corstars_tbl_xx(baseline, result="html")

followup<-aqol6d_tb[aqol6d_tb$round=="Follow-up",] %>% 
   dplyr::select(aqol6d_total_w, PHQ9 ,  BADS, GAD7 ,OASIS,  SCARED, K6 ) 

make_corstars_tbl_xx(followup, result="html")

``` 


