---
title: "Main Workflow"
output: html_document
params:
  path_to_data_1L_chr: !r NA_character_
  path_to_write_fls_to_1L_chr: "../../../../../../Data/Project/Utility_Models"
  dir_nm_1L_chr: "One_Predr_Output"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(xtable) 
library(FBaqol) 
library(magrittr)
```

# Specify input data

```{r}
if(!is.na(params$path_to_data_1L_chr)){
  raw_data_tb <- transform_raw_aqol_tb_to_aqol6d_tb(readRDS(params$path_to_data_1L_chr))
}else{
  raw_data_tb <- FBaqol::replication_popl_tb
}
path_to_write_fls_to_1L_chr <- params$path_to_write_fls_to_1L_chr
dir_nm_1L_chr <- params$dir_nm_1L_chr
path_to_write_to_1L_chr <- paste0(path_to_write_fls_to_1L_chr,
                                                      "/",
                                                      dir_nm_1L_chr)
```

# Test candidate models, predictors and covariates

```{r}
outp_smry_ls <- write_all_alg_outps(raw_data_tb = raw_data_tb,
                    path_to_write_to_1L_chr = path_to_write_to_1L_chr,
                    aqol6d_q_pfx_1L_chr = "aqol6d_q",
                    dep_var_nm_1L_chr = "aqol6d_total_w",
                    candidate_predrs_chr = c("BADS","GAD7","K6","OASIS","PHQ9","SCARED"),
                    candidate_covar_nms_chr = c("d_sex_birth_s", "SOFAS", "c_p_diag_s", "c_clinical_staging_s", "d_age",  "d_sexual_ori_s", "d_country_bir_s", "d_relation_s", "d_studying_working"),
                    id_var_nm_1L_chr ="fkClientID",
                    round_var_nm_1L_chr = "round",
                    round_bl_val_1L_chr = "Baseline",
                    mdl_types_chr = FBaqol::mdl_types_lup$short_name_chr, 
                    prefd_mdl_types_chr = c("GLM_GSN_LOG","OLS_CLL"),
                    choose_from_pfx_chr = c("GLM","OLS", "BET"),
                    prefd_covars_chr = NA_character_,
                    seed_1L_int = 12345,
                    n_folds_1L_int = 10L,
                    max_nbr_of_boruta_mdl_runs_int = 300L,
                    mdl_types_lup = NULL)

```

# Apply selected models to selected predictors

```{r}
outp_smry_ls <- write_ts_mdls_from_alg_outp(outp_smry_ls,
                                            fn_ls = list(fit_gsn_log_lnk,fit_clg_log_tfmn),
                                            backend_1L_chr = "cmdstanr",
                                            iters_1L_int = 1000L)
```

# Create shareable version of predictive models

```{r}
outp_smry_ls <- write_shareable_mdls(outp_smry_ls)
```

# Predict

```{r}
fk_data_tb <- make_fake_ts_data(outp_smry_ls)
fk_data_tb %>%
  dplyr::mutate(!!rlang::sym(outp_smry_ls$dep_var_nm_1L_chr) := predict_aqol6d(data_tb = fk_data_tb,
               tfmn_1L_chr = "CLL",
               mdl = outp_smry_ls$sharble_mdls_ls$PHQ9_1_OLS_CLL)) %>% head() 
```

# Save work

```{r}
outp_smry_ls$fk_data_tb <- fk_data_tb
saveRDS(outp_smry_ls,paste0(outp_smry_ls$path_to_write_to_1L_chr,"/I_ALL_OUTPUT_.RDS"))
```

