---
title: "Main Workflow"
output: html_document
params:
  path_to_data_1L_chr: !r NA_character_
  path_to_write_fls_to_1L_chr: "../../../../../../Data/Project/Utility_Models"
  dir_nm_1L_chr: "One_Predr_Output"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(xtable) 
library(FBaqol) 
library(magrittr)
```

```{r}
seed_1L_int <- 12345
set.seed(seed_1L_int)
```
```{r}
if(!is.na(params$path_to_data_1L_chr)){
  raw_data_tb <- transform_raw_aqol_tb_to_aqol6d_tb(readRDS(params$path_to_data_1L_chr))
}else{
  raw_data_tb <- FBaqol::replication_popl_tb
}
```
```{r}
path_to_write_fls_to_1L_chr <- params$path_to_write_fls_to_1L_chr
dir_nm_1L_chr <- params$dir_nm_1L_chr
path_to_write_to_1L_chr <- paste0(path_to_write_fls_to_1L_chr,
                                                      "/",
                                                      dir_nm_1L_chr)
dep_var_nm_1L_chr <- "aqol6d_total_w"
candidate_predrs_chr <- c("BADS","GAD7","K6","OASIS","PHQ9","SCARED")
covar_var_nms_chr <- c("d_sex_birth_s", "SOFAS", "c_p_diag_s", "c_clinical_staging_s", "d_age",  "d_sexual_ori_s", "d_country_bir_s", "d_relation_s", "d_studying_working")
n_folds_1L_int <- 10L
round_var_nm_1L_chr <- "round"
round_bl_val_1L_chr <- "Baseline"
prefd_mdl_types_chr <- c("GLM_GSN_LOG","OLS_CLL")
choose_from_pfx_chr = c("GLM","OLS", "BET") ## Default
#prefd_covars_chr <- "SOFAS"
id_var_nm_1L_chr <-"fkClientID"
mdl_types_chr <- FBaqol::mdl_types_lup$short_name_chr[3:14]
max_nbr_of_boruta_mdl_runs_int <- 300L
```

```{r}
scored_data_tb <- add_adol6d_scores(raw_data_tb,
                              prefix_1L_chr =  "aqol6d_q",
                              id_var_nm_1L_chr = id_var_nm_1L_chr,
                              wtd_aqol_var_nm_1L_chr = dep_var_nm_1L_chr) 
```

```{r}
bl_tb <- transform_ds_for_tstng(scored_data_tb, dep_var_nm_1L_chr = dep_var_nm_1L_chr, candidate_predrs_chr = candidate_predrs_chr, dep_var_max_val_1L_dbl = 0.999, round_val_1L_chr = "Baseline")
```

```{r}
candidate_predrs_chr <- reorder_cndt_predrs_chr(candidate_predrs_chr,
                        data_tb = bl_tb,
                        dep_var_nm_1L_chr = dep_var_nm_1L_chr)
predr_var_nm_1L_chr <- candidate_predrs_chr[1]
predr_var_desc_1L_chr <- candidate_predrs_lup %>% ready4fun::get_from_lup_obj(match_value_xx = predr_var_nm_1L_chr, match_var_nm_1L_chr = "short_name_chr", target_var_nm_1L_chr = "long_name_chr", evaluate_lgl = F)
predr_vals_dbl <- make_predr_vals(predr_var_nm_1L_chr,
                                  candidate_predrs_lup = candidate_predrs_lup)

```

```{r}
bc_plt_path_1L_chr <- write_box_cox_tfmn(data_tb = bl_tb, 
                    predr_var_nm_1L_chr = predr_var_nm_1L_chr, 
                    path_to_write_to_1L_chr = path_to_write_to_1L_chr) # ,mdl_types_lup = mdl_types_lup
```

```{r}
smry_of_sngl_predr_mdls_tb <- write_sngl_predr_multi_mdls_outps(data_tb = bl_tb,
                                                          n_folds_1L_int = n_folds_1L_int,
                                                          mdl_types_chr = mdl_types_chr,
                                                          dep_var_nm_1L_chr = dep_var_nm_1L_chr,
                                                          predr_var_nm_1L_chr = predr_var_nm_1L_chr,
                                                          predr_var_desc_1L_chr = predr_var_nm_1L_chr,
                                                          predr_vals_dbl = predr_vals_dbl , 
                                                          path_to_write_to_1L_chr = path_to_write_to_1L_chr) # ,mdl_types_lup = mdl_types_lup

```

```{r}
if(is.na(prefd_mdl_types_chr[1])){
  prefd_mdl_types_chr <- make_prefd_mdls_vec(smry_of_sngl_predr_mdls_tb,
                    choose_from_pfx_chr = choose_from_pfx_chr)
}
```


```{r}
predr_cmprsns_tb <- write_predr_cmprsn_outps(data_tb = bl_tb,
                                             path_to_write_to_1L_chr = path_to_write_to_1L_chr,
                                             dep_var_nm_1L_chr = dep_var_nm_1L_chr,
                                             candidate_predrs_chr = candidate_predrs_chr,
                                             max_nbr_of_boruta_mdl_runs_int = max_nbr_of_boruta_mdl_runs_int)

```

```{r}
smry_of_mdl_sngl_predrs_tb <- write_mdl_type_multi_outps(data_tb = bl_tb,
                            n_folds_1L_int = n_folds_1L_int,
                            predrs_var_nms_chr = predr_cmprsns_tb$predr_chr,
                            mdl_type_1L_chr = prefd_mdl_types_chr[1],
                            dep_var_nm_1L_chr = dep_var_nm_1L_chr,
                            path_to_write_to_1L_chr = path_to_write_to_1L_chr) # mdl_types_lup = mdl_types_lup
```

```{r}
bl_tb <- scored_data_tb %>% transform_ds_for_tstng(candidate_predrs_chr = candidate_predrs_chr, 
                                   covar_var_nms_chr = covar_var_nms_chr,
                                   remove_all_mssng_1L_lgl = T,
                                   round_val_1L_chr = round_bl_val_1L_chr)
mdls_with_covars_smry_tb <- write_mdl_type_covars_mdls(bl_tb,
                       predrs_var_nms_chr = candidate_predrs_chr,
                       covar_var_nms_chr = covar_var_nms_chr,
                       mdl_type_1L_chr = prefd_mdl_types_chr[1],
                       path_to_write_to_1L_chr = path_to_write_to_1L_chr,
                       fl_nm_pfx_1L_chr = "CT") # ,                       mdl_types_lup = mdl_types_lup
signt_covars_chr <- get_signft_covars(mdls_with_covars_smry_tb = mdls_with_covars_smry_tb,
                       covar_var_nms_chr)
if(is.na(prefd_covars_chr))
  prefd_covars_chr <- signt_covars_chr

```
```{r}
dud_tb <- write_mdl_type_multi_outps(data_tb = bl_tb,
                            n_folds_1L_int = NULL,
                            start_1L_chr = NA_character_,
                            predrs_var_nms_chr = predr_cmprsns_tb$predr_chr,
                            covar_var_nms_chr = covar_var_nms_chr,
                            mdl_type_1L_chr = prefd_mdl_types_chr[2],
                            dep_var_nm_1L_chr = dep_var_nm_1L_chr,
                            path_to_write_to_1L_chr = path_to_write_to_1L_chr,
                            #mdl_types_lup = mdl_types_lup,
                            fl_nm_pfx_1L_chr = "E_CK_CV")
```
