---
title: "Untitled"
output: html_document
params:
  output_type_1L_chr: HTML
  mdl_smry_dir_1L_chr: ../../../../../../Data/Project/Utility_Models
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(comment=NA)
#knitr::opts_chunk$set(output.dir = paste0(params$mdl_smry_dir_1L_chr))
library(kableExtra)
library(flextable)
library(xtable) # EDIT
library(FBaqol) # EDIT
library(magrittr)
options(tinytex.verbose = TRUE)
options(xtable.floating = FALSE)
options(xtable.timestamp = "")
```

```{r echo=FALSE}
predr_vars_nms_ls <- make_predr_vars_nms_ls(main_predrs_chr = c("BADS","GAD7","K6","OASIS","PHQ9","SCARED"),
                       covars_ls = list("SOFAS"))
knit_pars_ls <- make_knit_pars_ls(mdl_smry_dir_1L_chr = params$mdl_smry_dir_1L_chr,
                  mdl_types_chr = c("GSN_LOG","CLL_TFN"),
                  predr_vars_nms_ls = predr_vars_nms_ls,
                  output_type_1L_chr = params$output_type_1L_chr
                  )
```

```{r, echo=FALSE, results='asis'}
#knit_mdl_rprt(knit_pars_ls[[11]])
 knit_pars_ls %>%
  purrr::walk(~knit_mdl_rprt(.x))
```

