---
title: "_Make_Suplry_Mdls"
author: "Matthew Hamilton & Caroline Gao"
date: "18/03/2021"
output: html_document
---

# Workspace edits

```{r}
# sup_outp_1_dir_1L_chr <- paste0(here::here("Analyses/AQoL-6D/AQol_6D longitudinal"),"/Sup_Output_1")
# sup_outp_2_dir_1L_chr <- paste0(here::here("Analyses/AQoL-6D/AQol_6D longitudinal"),"/Sup_Output_2")
# purrr::walk(c(sup_outp_1_dir_1L_chr,sup_outp_2_dir_1L_chr),
#             ~ if(!dir.exists(.x))
#               dir.create(.x))

```
```{r eval=FALSE}
# dv_ls <- list(dv_nm_1L_chr = "firstbounce",
#                                ds_url_1L_chr = "https://doi.org/10.7910/DVN/BAMRIP", 
#                                parent_dv_dir_1L_chr = "../../../../Data/Dataverse")
```
```{r}
mdl_types_lup <- TTU::get_cndts_for_mxd_mdls()
```

## SOFAS Additions
```{r}
# outp_dir_1L_chr <- sup_outp_1_dir_1L_chr
```
```{r}
# ds_smry_ls <- list(candidate_predrs_chr = youthu::predictors_lup$short_name_chr[youthu::predictors_lup$short_name_chr=="SOFAS"],
#                    candidate_covar_nms_chr = c("d_sex_birth_s", "c_p_diag_s", "c_clinical_staging_s", "d_age",  "d_sexual_ori_s", "d_country_bir_s", "d_relation_s", "d_studying_working"),
#                    depnt_var_nm_1L_chr = "aqol6d_total_w",
#                    id_var_nm_1L_chr = "fkClientID",
#                    round_var_nm_1L_chr = "round",
#                    round_bl_val_1L_chr = "Baseline")
# data("predictors_lup", package = "youthu")
# ds_smry_ls$predictors_lup <- predictors_lup
```
```{r}
mdl_smry_ls <- list(mdl_types_lup = mdl_types_lup,
                    mdl_types_chr = mdl_types_lup$short_name_chr,
                    folds_1L_int = 10L,
                    prefd_mdl_types_chr = c("GLM_GSN_LOG","OLS_CLL"),
                    prefd_covars_chr = NA_character_,
                    max_nbr_of_boruta_mdl_runs_int = 300L,
                    choose_from_pfx_chr = c("GLM","OLS"))
```
```{r, child=c('_Write_Suplry_Analysis.Rmd')}
```


## Anxiety + Depression Additions
```{r}
outp_dir_1L_chr <- sup_outp_2_dir_1L_chr
```
```{r}
ds_smry_ls <- list(candidate_predrs_chr = youthu::predictors_lup$short_name_chr[youthu::predictors_lup$short_name_chr %in% c("SCARED","OASIS","GAD7")],
                   candidate_covar_nms_chr = c("BADS", "d_sex_birth_s", "SOFAS", "c_p_diag_s", "c_clinical_staging_s",
                                               "d_age",  "d_sexual_ori_s", "d_country_bir_s", "d_relation_s",
                                               "d_studying_working"),
                   depnt_var_nm_1L_chr = "aqol6d_total_w",
                   id_var_nm_1L_chr = "fkClientID",
                   round_var_nm_1L_chr = "round",
                   round_bl_val_1L_chr = "Baseline")
data("predictors_lup", package = "youthu")
ds_smry_ls$predictors_lup <- predictors_lup
```

```{r}
mdl_smry_ls <- list(mdl_types_lup = mdl_types_lup,
                    mdl_types_chr = mdl_types_lup$short_name_chr,
                    folds_1L_int = 10L,
                    prefd_mdl_types_chr = c("GLM_GSN_LOG","OLS_CLL"),
                    prefd_covars_chr = "BADS",
                    max_nbr_of_boruta_mdl_runs_int = 300L,
                    choose_from_pfx_chr = c("GLM","OLS"))
```
```{r, child=c('_Write_Suplry_Analysis.Rmd')}
```


