---
title: "AQol-6D analyses"
output:
  html_document: 
    code_folding: "hide"
    toc: yes 
  output: html_notebook
params:
  path_to_data_1L_chr: "../Data/fake_pop_tb.rds"
  path_to_write_fls_to_1L_chr: "../../../../../../../Data/Project/Utility_Models"
  dir_nm_1L_chr: "One_Predr_Output"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(xtable) 
library(TTU) 
library(magrittr)
```

```{r}
set.seed(12345)
```

```{r}
path_to_write_fls_to_1L_chr <- params$path_to_write_fls_to_1L_chr
dir_nm_1L_chr <- params$dir_nm_1L_chr
path_to_write_to_1L_chr <- paste0(path_to_write_fls_to_1L_chr,
                                                      "/",
                                                      dir_nm_1L_chr)
dep_var_nm_1L_chr <- "aqol6d_total_w"
candidate_predrs_chr <- c("BADS","GAD7","K6","OASIS","PHQ9","SCARED")
covar_var_nms_chr <- c("d_sex_birth_s", "SOFAS", "c_p_diag_s", "c_clinical_staging_s", "d_age",  "d_sexual_ori_s", "d_country_bir_s", "d_relation_s", "d_studying_working")
n_folds_1L_int <- 10L
round_var_nm_1L_chr <- "round"
round_bl_val_1L_chr <- "Baseline"
prefd_mdl_types_chr <- c("OLS_CLL", "GLM_GSN_LOG")
prefd_covars_chr <- "SOFAS"
```

```{r}
data_tb <- transform_raw_aqol_tb_to_aqol6d_tb(readRDS(params$path_to_data_1L_chr))
bl_tb <- transform_ds_for_tstng(data_tb, dep_var_nm_1L_chr = dep_var_nm_1L_chr, candidate_predrs_chr = candidate_predrs_chr, dep_var_max_val_1L_dbl = 0.999, round_val_1L_chr = "Baseline")
```

```{r}
bc_plt_path_1L_chr <- write_box_cox_tfmn(data_tb = bl_tb, 
                    predr_var_nm_1L_chr = "PHQ9", 
                    path_to_write_to_1L_chr = path_to_write_to_1L_chr, 
                    mdl_types_lup = mdl_types_lup) 
```

```{r}
smry_of_sngl_predr_mdls_tb <- write_sngl_predr_multi_mdls_outps(data_tb = bl_tb,
                                                          n_folds_1L_int = n_folds_1L_int,
                                                          mdl_types_chr = c("OLS_NTF","OLS_LOG", "OLS_LOGIT", "OLS_LOGLOG", "OLS_CLL", "GLM_GSN_LOG", "GLM_BNL_LOG", "GLM_BNL_LGT", "GLM_BNL_CLL", "BET_LOG","BET_LGT", "BET_CLL"),
                                                          dep_var_nm_1L_chr = "aqol6d_total_w",
                                                          predr_var_nm_1L_chr = "PHQ9",
                                                          predr_var_desc_1L_chr = "PHQ9 total score",
                                                          predr_vals_dbl = 0:27, 
                                                          path_to_write_to_1L_chr = path_to_write_to_1L_chr,
                                                          mdl_types_lup = mdl_types_lup)
```

```{r}
predr_cmprsns_tb <- write_predr_cmprsn_outps(data_tb = bl_tb,
                                             path_to_write_to_1L_chr = path_to_write_to_1L_chr,
                                             dep_var_nm_1L_chr = "aqol6d_total_w",
                                             candidate_predrs_chr = candidate_predrs_chr,
                                             max_nbr_of_boruta_mdl_runs_int = 300L)

```

```{r}
smry_of_mdl_sngl_predrs_tb <- write_mdl_type_multi_outps(data_tb = bl_tb,
                            n_folds_1L_int = n_folds_1L_int,
                            predrs_var_nms_chr = predr_cmprsns_tb$predr_chr,
                            mdl_type_1L_chr = "GLM_GSN_LOG",
                            dep_var_nm_1L_chr = "aqol6d_total_w",
                            path_to_write_to_1L_chr = path_to_write_to_1L_chr,
                            mdl_types_lup = mdl_types_lup)
```

```{r}
bl_tb <- data_tb %>% transform_ds_for_tstng(candidate_predrs_chr = candidate_predrs_chr, 
                                   covar_var_nms_chr = covar_var_nms_chr,
                                   remove_all_mssng_1L_lgl = T,
                                   round_val_1L_chr = "Baseline")
mdls_with_covars_smry_tb <- write_mdl_type_covars_mdls(bl_tb,
                       predrs_var_nms_chr = candidate_predrs_chr,
                       covar_var_nms_chr = covar_var_nms_chr,
                       mdl_type_1L_chr = prefd_mdl_types_chr[2],
                       path_to_write_to_1L_chr = path_to_write_to_1L_chr,
                       fl_nm_pfx_1L_chr = "CT",
                       mdl_types_lup = mdl_types_lup)

signt_covars_chr <- get_signft_covars(mdls_with_covars_smry_tb = mdls_with_covars_smry_tb,
                       covar_var_nms_chr)
if(is.na(prefd_covars_chr))
  prefd_covars_chr <- signt_covars_chr

```

```{r}
smry_of_mdl_sngl_predrs_tb <- write_mdl_type_multi_outps(data_tb = bl_tb,
                            n_folds_1L_int = NULL,
                            start_1L_chr = NA_character_,
                            predrs_var_nms_chr = predr_cmprsns_tb$predr_chr,
                            covar_var_nms_chr = covar_var_nms_chr,
                            mdl_type_1L_chr = prefd_mdl_types_chr[2],
                            dep_var_nm_1L_chr = dep_var_nm_1L_chr,
                            path_to_write_to_1L_chr = path_to_write_to_1L_chr,
                            mdl_types_lup = mdl_types_lup,
                            fl_nm_pfx_1L_chr = "E_CK_CV")
```


