---
title: "Summary of Models"
output:
  pdf_document: default
  html_document: default
params:
  covars_ls: !r NULL
  main_predrs_chr: !r NA_character_
  mdl_smry_dir_1L_chr: ../Output
  mdl_types_chr: !r NA_character_
  output_type_1L_chr: HTML
  root_dir_1L_chr: ./
  section_type_1L_chr: "#"
---

```{r setup, include=FALSE}
library(ready4u)
library(magrittr)
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(comment = NA)
knitr::opts_knit$set(root.dir = params$root_dir_1L_chr)
options(tinytex.verbose = TRUE)
options(xtable.floating = FALSE)
options(xtable.timestamp = "")
```

```{r echo=FALSE}
predr_vars_nms_ls <- make_predr_vars_nms_ls(main_predrs_chr = params$main_predrs_chr, #c("BADS","GAD7","K6","OASIS","PHQ9","SCARED"),
                       covars_ls = params$covars_ls #list("SOFAS")
                       )
knit_pars_ls <- make_knit_pars_ls(mdl_smry_dir_1L_chr = params$mdl_smry_dir_1L_chr,
                  mdl_types_chr = params$mdl_types_chr,#c("GSN_LOG","CLL_TFN"),
                  predr_vars_nms_ls = predr_vars_nms_ls,
                  output_type_1L_chr = params$output_type_1L_chr,
                  section_type_1L_chr = params$section_type_1L_chr
                  ) 
```

```{r, echo=FALSE, results='asis'}
 knit_pars_ls %>%
  purrr::walk(~knit_mdl_rprt(.x, path_to_mdl_rprt_tmpl_1L_chr = "_mdl_rpt_tmpl.Rmd"))
```

