---
title: "AQoL 6D Model Summary"
author: "Matthew Hamilton & Caroline Gao"
date: "24/10/2020"
output:
  html_document: 
    code_folding: "hide"
    toc: yes 
---

```{r setup, include=FALSE}
options(brms.backend = "cmdstanr")
knitr::opts_chunk$set(echo = TRUE)
library(xtable) # EDIT
library(FBaqol) # EDIT
library(magrittr)
```

```{r}
data_tb <- transform_raw_aqol_tb_to_aqol6d_tb(readRDS("../Data/fake_pop_tb.rds"))
```

```{r}
mdl_smry_dir_1L_chr <- "../../../../../../../Data/Project/Utility_Models"
mdl_types_chr <- c("GSN_LOG","CLL_TFN")
make_predr_vars_nms_ls(main_predrs_chr = c("BADS","GAD7","K6","OASIS","PHQ9","SCARED"),
                       covars_ls = list("SOFAS"))
fn_ls <- list(fit_gsn_log_lnk,fit_clg_log_tfmn)
mdl_nms_ls <- predictor_vars_nms_ls %>% purrr::map(~make_mdl_nms_ls(list(.x),
                              mdl_types_chr = mdl_types_chr)) %>% 
  purrr::flatten()
#mdl_nm_chr <- paste0(predictor_vars_nms_ls[[1]][1],"_",mdl_types_chr)
```

```{r, results="asis"}
if(!dir.exists("../../../../../../../Data/Project/Utility_Models"))
  dir.create("../../../../../../../Data/Project/Utility_Models/")
# https://web.archive.org/web/20200808073714/https://helpdeskgeek.com/windows-10/add-windows-path-environment-variable/
# note use actual rtools path
# https://web.archive.org/web/20200813122856/https://www.maxmantei.com/blog/2020-05-16-installing-cmdstanr-on-windows/cmdstanr-windows/
# use syu
# https://discourse.mc-stan.org/t/problem-running-rstan-with-r-4-0-2/17257/17
mdls_smry_tb <- purrr::map_dfr(1:length(mdl_nms_ls),
                                ~ {
                                  idx_1L_int <- .x
                                    purrr::map2_dfr(fn_ls,
                                                    mdl_nms_ls[[idx_1L_int]],
                                                    ~ {
                                                      smry_ls <- make_smry_of_ts_mdl(data_tb = data_tb,
                                                       fn = .x,
                                                       predictor_vars_nms_chr = predictor_vars_nms_ls[[idx_1L_int]],
                                                       mdl_nm_1L_chr = .y,
                                                       path_to_write_to_1L_chr = mdl_smry_dir_1L_chr,
                                                       iters_1L_int = 4000L,
                                                       seed_1L_int = 1000L)
                                                      Sys.sleep(15)
                                                      smry_ls$smry_of_ts_mdl_tb
                                  })
                                })
  

```




# ```{r results="asis"}
# tb_2 <- make_smry_of_ts_mdl(data_tb = data_tb,
#                                                        fn = fn_ls[[2]],
#                                                        predictor_vars_nms_chr = c("PHQ9","SOFAS"),
#                                                        mdl_nm_1L_chr = mdl_nm_chr[2],
#                                                        path_to_write_to_1L_chr = "../../../../../../../Data/Project/Utility_Models",
#                                                        iters_1L_int = 4000L,
#                                                        seed_1L_int = 1000L)
# ```
# 
# ```{r}
# tb_2
# ```
# 
# ```{r results="asis"}
# tb_1 <- make_smry_of_ts_mdl(data_tb = data_tb,
#                                                        fn = fn_ls[[1]],
#                                                        predictor_vars_nms_chr = c("PHQ9","SOFAS"),
#                                                        mdl_nm_1L_chr = mdl_nm_chr[1],
#                                                        path_to_write_to_1L_chr = "../../../../../../../Data/Project/Utility_Models",
#                                                        iters_1L_int = 4000L,
#                                                        seed_1L_int = 1000L)
# ```
# ```{r}
# tb_1
# ```

