---
title: "Untitled"
author: "Matthew Hamilton & Caroline Gao"
date: "24/10/2020"
output: 
  html_document:
    fig_caption: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(xtable) # EDIT
library(FBaqol) # EDIT
library(magrittr)
```

```{r child="./AQoL_6D_Replication_Fns.Rmd", echo=FALSE}

```

```{r, include=FALSE}
mdl_ls <- readRDS("../../../../../../../Data/Project/Utility_Models/PHQ9_GSN_LOG.RDS")
fn <- fit_gsn_log_lnk
data_tb <- transform_raw_aqol_tb_to_aqol6d_tb(readRDS("../Data/fake_pop_tb.rds"))
tfd_data_tb <- transform_tb_to_mdl_inp(data_tb,
                                    predictor_vars_nms_chr = c("PHQ9","SOFAS"))
dep_var_nm_1L_chr <- "aqol6d_total_w"
tfd_dep_var_nm_1L_chr <- transform_dep_var_nm_for_cll(dep_var_nm_1L_chr)
mdl_plts_ls <- make_brm_model_plts(brm_model_ls =  mdl_ls,
                                   data_tb = tfd_data_tb,
                                   dep_var_nm_1L_chr = tfd_dep_var_nm_1L_chr,
                                   tfmn_fn = ifelse(identical(fn,fit_gsn_log_lnk),
                                                        function(x){x},
                                                        function(x){1-exp(-exp(x))})) %>%
  stats::setNames(c("A","B","C","D"))

```

```{r, fig.cap=c("Caption 1", "Caption 2", "Caption 3"), echo=FALSE, message=F}

cat('\n') 
cat("###", "TEST", "\n\n")

for(plots in mdl_plts_ls){
  print(mdl_plts_ls)
  cat('\n\n') 
}


```
