---
title: "AQol-6D analyses"
output:
  html_document: 
    code_folding: "hide"
    toc: yes 
  output: html_notebook
params:
  path_to_data_1L_chr: "../Data/fake_pop_tb.rds"
  path_to_write_fls_to_1L_chr: "../../../../../../../Data/Project/Utility_Models"
  dir_nm_1L_chr: "One_Predr_Output"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(xtable) # EDIT
library(FBaqol) # EDIT
library(magrittr)
```

```{r}
get_significant_covars <- function(mdls_with_covars_smry_tb,
                                   covar_var_nms_chr){
  signif_vars_chr <- mdls_with_covars_smry_tb$Significant %>% purrr::map(~strsplit(.x, " ")) %>% purrr::flatten() %>% purrr::flatten_chr() %>% unique()
signt_covars_chr <- covar_var_nms_chr[covar_var_nms_chr %in% signif_vars_chr]
return(signt_covars_chr)
}
make_one_predr_mdl <- function(data_tb,
                               dep_var_nm_1L_chr = "aqol6d_total_w",
                               tfmn_1L_chr = "NTF",
                               predr_var_nm_1L_chr,
                               covar_var_nms_chr = NA_character_,
                               mdl_type_1L_chr = "OLS_NTF",
                               mdl_types_lup = NULL,
                               control_1L_chr = NA_character_,
                               start_1L_chr = NULL){
      if(is.null(mdl_types_lup))
      mdl_types_lup <- data("mdl_types_lup", package = "FBaqol", envir = environment())
  data_tb <- data_tb %>%
    dplyr::filter(!is.na(!!rlang::sym(predr_var_nm_1L_chr))) 
  if(is.null(start_1L_chr)){
        start_1L_chr <- ready4fun::get_from_lup_obj(mdl_types_lup,
                                                   match_var_nm_1L_chr = "short_name_chr",
                                                   match_value_xx = mdl_type_1L_chr,
                                                   target_var_nm_1L_chr = "start_chr",
                                                   evaluate_lgl = F)
  }
    if(!is.na(control_1L_chr)){
      idx_1L_int <- 1 + stringi::stri_locate_last_fixed(mdl_type_1L_chr,"_")[1,1] %>% as.vector()
      link_1L_chr <- stringr::str_sub(mdl_type_1L_chr, start = idx_1L_int)
      link_1L_chr <- ifelse(link_1L_chr=="LOG",
                            "log",
                            ifelse(link_1L_chr == "LGT",
                                   "logit",
                                   ifelse(link_1L_chr == "CLL",
                                          "cloglog",
                                          "ERROR")))
    }
  mdl_1L_chr <- paste0(ready4fun::get_from_lup_obj(mdl_types_lup,
                                                   match_var_nm_1L_chr = "short_name_chr",
                                                   match_value_xx = mdl_type_1L_chr,
                                                   target_var_nm_1L_chr = "fn_chr",
                                                   evaluate_lgl = F),
                       "(",
                       transform_dep_var_nm(dep_var_nm_1L_chr, tfmn_1L_chr = tfmn_1L_chr),
                       " ~ ",
                       predr_var_nm_1L_chr, 
                       ifelse(is.na(covar_var_nms_chr[1]),
                              "",
                              paste0(" + ",paste0(covar_var_nms_chr, collapse = " + "))),
                       ", data = data_tb",
                       ifelse(!is.na(ready4fun::get_from_lup_obj(mdl_types_lup,
                                                   match_var_nm_1L_chr = "short_name_chr",
                                                   match_value_xx = mdl_type_1L_chr,
                                                   target_var_nm_1L_chr = "family_chr",
                                                   evaluate_lgl = F)),
                              paste0(", family = ", 
                                     ready4fun::get_from_lup_obj(mdl_types_lup,
                                                   match_var_nm_1L_chr = "short_name_chr",
                                                   match_value_xx = mdl_type_1L_chr,
                                                   target_var_nm_1L_chr = "family_chr",
                                                   evaluate_lgl = F)),
                              ""),
                       ifelse(!is.na(start_1L_chr),
                              ", ",
                              ""),
                       ifelse(!is.na(control_1L_chr),
                              paste0("link=\"",link_1L_chr,"\",control=",control_1L_chr,"("),
                              ""),
                       ifelse(!is.na(start_1L_chr),
                              paste0("start=c(",
                                     start_1L_chr,
                                     ")"),
                              ""),
                                              ifelse(!is.na(control_1L_chr),
                              ")",
                              ""),
                       ")")
  mdl <- eval(parse(text = mdl_1L_chr))
  return(mdl)
}
make_predn_ds_with_one_predr <- function(mdl,
                                         dep_var_nm_1L_chr = "aqol6d_total_w",
                                         tfmn_1L_chr = "NTF",
                                         predr_var_nm_1L_chr,
                                         predr_vals_dbl,
                                         pred_type_1L_chr = NULL){
  predn_ds_tb <- tibble::tibble(!!rlang::sym(predr_var_nm_1L_chr) := predr_vals_dbl)
  predn_ds_tb <- predn_ds_tb %>% dplyr::mutate(!!rlang::sym(dep_var_nm_1L_chr) := predict(mdl, newdata = predn_ds_tb, type = pred_type_1L_chr) %>% calculate_dep_var_tfmn(tfmn_1L_chr = tfmn_1L_chr, tfmn_is_outp_1L_lgl = T))
  return(predn_ds_tb)
}
make_smry_of_one_predr_mdl <- function(data_tb,
                                       mdl,
                                       folds_ls,
                                       dep_var_nm_1L_chr = "aqol6d_total_w",
                                       tfmn_1L_chr = "NTF",
                                       predr_var_nm_1L_chr,
                                       mdl_type_1L_chr = "OLS_NTF",
                                       mdl_types_lup = NULL,
                                       pred_type_1L_chr = NULL){
    if(is.null(mdl_types_lup))
      mdl_types_lup <- data("mdl_types_lup", package = "FBaqol", envir = environment())
    data_tb <- data_tb %>%
        dplyr::filter(!is.na(!!rlang::sym(predr_var_nm_1L_chr))) 
    mdl_desc_1L_chr <- ready4fun::get_from_lup_obj(mdl_types_lup,
                                                   match_var_nm_1L_chr = "short_name_chr",
                                                   match_value_xx = mdl_type_1L_chr,
                                                   target_var_nm_1L_chr = "long_name_chr",
                                                   evaluate_lgl = F)

smry_of_one_predr_mdl_tb <- purrr::map_dfr(folds_ls,
               ~ {
                   mdl <- make_one_predr_mdl(data_tb,
                               dep_var_nm_1L_chr = dep_var_nm_1L_chr,
                               tfmn_1L_chr = tfmn_1L_chr,
                               predr_var_nm_1L_chr = predr_var_nm_1L_chr,
                               mdl_type_1L_chr = mdl_type_1L_chr,
                               mdl_types_lup = mdl_types_lup) 
  pred_old_dbl <- predict(mdl, type = pred_type_1L_chr)
  pred_new_dbl <- predict(mdl,newdata = data_tb[.x,], type = pred_type_1L_chr) %>% calculate_dep_var_tfmn(tfmn_1L_chr = tfmn_1L_chr,
                                                                               tfmn_is_outp_1L_lgl = T)
  tibble::tibble(Rsquared = caret::R2(pred_old_dbl, data_tb[-.x,] %>% dplyr::pull(!!rlang::sym(dep_var_nm_1L_chr)), form = "traditional"),
  RMSE = caret::RMSE(pred_old_dbl, data_tb[-.x,] %>% dplyr::pull(!!rlang::sym(dep_var_nm_1L_chr))),
  MAE = caret::MAE(pred_old_dbl, data_tb[-.x,] %>% dplyr::pull(!!rlang::sym(dep_var_nm_1L_chr))),
  RsquaredP = caret::R2(pred_new_dbl, data_tb[.x,] %>% dplyr::pull(!!rlang::sym(dep_var_nm_1L_chr)), form = "traditional"),
  RMSEP = caret::RMSE(pred_new_dbl, data_tb[.x,] %>% dplyr::pull(!!rlang::sym(dep_var_nm_1L_chr))),
  MAEP = caret::MAE(pred_new_dbl, data_tb[.x,] %>% dplyr::pull(!!rlang::sym(dep_var_nm_1L_chr))))
               }
) %>% dplyr::summarise_all(mean) %>%
    dplyr::mutate(Model = mdl_desc_1L_chr) %>%
    dplyr::select(Model, dplyr::everything())
return(smry_of_one_predr_mdl_tb)
}
library(ggfortify)
plot_auto_lm <- function(mdl, # Requires ggfortify
                         which_dbl = 1:6, 
                         ncol_1L_int = 3L, 
                         label_size_1L_int = 3){
 plt <- ggplot2::autoplot(mdl,which = which_dbl, ncol = ncol_1L_int, label.size = label_size_1L_int)
if(6 %in% which_dbl)
  plt[which(which_dbl==6)] <- plt[which(which_dbl==6)] + ggtitle("Cooks vs Leverage") 
plt
}
plot_lnr_cmprsn <- function(data_tb,
                      predn_ds_tb,
                      dep_var_nm_1L_chr = "aqol6d_total_w",
                      predr_var_nm_1L_chr,
                      dep_var_desc_1L_chr = "AQoL-6D utility score",
                      predr_var_desc_1L_chr){
      data_tb <- data_tb %>%
        dplyr::filter(!is.na(!!rlang::sym(predr_var_nm_1L_chr)))
      
  ggplot2::ggplot(data_tb,ggplot2::aes(x = !!rlang::sym(predr_var_nm_1L_chr), y = !!rlang::sym(dep_var_nm_1L_chr) )) +
  ggplot2::geom_point() + 
  ggplot2::geom_smooth(method = "loess", size = 1.5) +
  ggplot2::geom_line(data = predn_ds_tb, ggplot2::aes(x = !!rlang::sym(predr_var_nm_1L_chr), y = !!rlang::sym(dep_var_nm_1L_chr)),col="red")  +
  ggplot2::theme_bw() + ggplot2::labs(x= predr_var_desc_1L_chr, y= dep_var_desc_1L_chr)
}
plot_sctr_lnr_cmprsn <- function(tfd_data_tb,
                                 dep_var_nm_1L_chr = "aqol6d_total_w",
                                 predd_val_var_nm_1L_chr = "Predicted"){
  tfd_data_tb %>%
    ggplot2::ggplot(ggplot2::aes(x = !!rlang::sym(dep_var_nm_1L_chr),
                             y = !!rlang::sym(predd_val_var_nm_1L_chr))) +
  ggplot2::geom_point() + 
  ggplot2::geom_smooth(method = "loess", size = 1.5) +
  ggplot2::theme_bw() +
  ggplot2::geom_abline(intercept = 0, slope = 1, color="red", 
                       linetype="dashed", size=1.5) +
  ggplot2::xlim(0, 1) + ggplot2::ylim(0, 1)
}
transform_data_tb_for_cmprsn <- function(data_tb,
                                         mdl,
                                         dep_var_nm_1L_chr = "aqol6d_total_w",
                                         source_data_nm_1L_chr = "Original",
                                         tf_type_1L_chr = "Predicted",
                                         pred_type_1L_chr = NULL,
                                         tfmn_for_bnml_1L_lgl = F,
                                         family_1L_chr = NA_character_){
  if(tf_type_1L_chr == "Predicted")
    new_data_dbl <- predict(mdl, type = pred_type_1L_chr)
  if(tf_type_1L_chr == "Simulated" & !tfmn_for_bnml_1L_lgl)
    new_data_dbl <- simulate(mdl)$sim_1
  if(tf_type_1L_chr == "Simulated" & tfmn_for_bnml_1L_lgl)
    (predict(mdl)+rnorm(nrow(data_tb),0,sigma(mdl))) %>% 
    calculate_dep_var_tfmn(tfmn_1L_chr = ifelse(family_1L_chr =="quasibinomial(log)",
                                                "LOG",
                                                ifelse(family_1L_chr =="quasibinomial(logit)",
                                                       "LOGIT",
                                                       ifelse(family_1L_chr =="quasibinomial(cloglog)",
                                                              "CLL",
                                                              "NTF"))), 
                           tfmn_is_outp_1L_lgl = T)
  tfd_data_tb <- data_tb %>% 
    dplyr::mutate(!!rlang::sym(tf_type_1L_chr) := new_data_dbl,
         !!rlang::sym(source_data_nm_1L_chr) := !!rlang::sym(dep_var_nm_1L_chr))
  return(tfd_data_tb)
}
transform_ds_for_tstng <- function(data_tb,
                                   dep_var_nm_1L_chr = "aqol6d_total_w",
                                   dep_var_max_val_1L_dbl = 0.999,
                                   main_predrs_chr = NA_character_,
                                   covar_var_nms_chr = NA_character_,
                                   round_var_nm_1L_chr = "round",
                                   round_val_1L_chr = "Baseline",
                                   remove_all_mssng_1L_lgl = F){
  vars_to_keep_chr <- c(dep_var_nm_1L_chr, main_predrs_chr, covar_var_nms_chr) %>% purrr::discard(is.na)
  tfd_data_tb <- data_tb %>% 
   dplyr::filter(!!rlang::sym(round_var_nm_1L_chr) == round_val_1L_chr) %>% 
   dplyr::select(!!!rlang::syms(vars_to_keep_chr)) %>% 
  dplyr::mutate(!!rlang::sym(dep_var_nm_1L_chr) := ifelse(!!rlang::sym(dep_var_nm_1L_chr) == 1, 0.999, !!rlang::sym(dep_var_nm_1L_chr))) 
  if(remove_all_mssng_1L_lgl)
    tfd_data_tb <- tfd_data_tb %>% na.omit()
  return(tfd_data_tb)
}
write_box_cox_tfmn <- function(data_tb,
                               predr_var_nm_1L_chr,
                               path_to_write_to_1L_chr,
                               dep_var_nm_1L_chr = "aqol6d_total_w",
                               fl_nm_pfx_1L_chr = "RT",
                               height_1L_dbl = 6,
                               width_1L_dbl = 6,
                               mdl_types_lup = NULL){
        
  if(is.null(mdl_types_lup))
      mdl_types_lup <- data("mdl_types_lup", package = "FBaqol", envir = environment())
  mdl <- make_one_predr_mdl(data_tb, 
                            dep_var_nm_1L_chr = dep_var_nm_1L_chr, 
                            predr_var_nm_1L_chr = predr_var_nm_1L_chr , 
                            mdl_type_1L_chr = "OLS_NTF",
                            mdl_types_lup = mdl_types_lup)
  path_to_plot_1L_chr <- write_brm_mdl_plt_fl(plt_fn = MASS::boxcox,
                     fn_args_ls = list(mdl, plotit=T),
                     path_to_write_to_1L_chr = path_to_write_to_1L_chr,
                     plt_nm_1L_chr = paste0(fl_nm_pfx_1L_chr,
                                            "_",
                                            predr_var_nm_1L_chr,
                                            "_",
                                            "boxcox"),
                     height_1L_dbl = height_1L_dbl,
                     width_1L_dbl = width_1L_dbl)
  return(path_to_plot_1L_chr)
  
}
write_mdl_sngl_predrs_outps <- function(data_tb,
                                       folds_ls,
                                       predr_var_nm_chr,
                                       # predr_var_desc_chr,
                                       # predr_vals_ls,
                                       mdl_type_1L_chr,
                                       dep_var_nm_1L_chr = "aqol6d_total_w",
                                       path_to_write_to_1L_chr,
                                       mdl_types_lup = NULL,
                                       fl_nm_pfx_1L_chr = "ind_predr"){
    if(is.null(mdl_types_lup))
      mdl_types_lup <- data("mdl_types_lup", package = "FBaqol", envir = environment())
  smry_of_mdl_sngl_predrs_tb <- purrr::map_dfr(predr_var_nm_chr,
               ~ {
                 tfmn_1L_chr <- ready4fun::get_from_lup_obj(mdl_types_lup, 
                                             match_var_nm_1L_chr = "short_name_chr",
                                             match_value_xx = mdl_type_1L_chr,
                                             target_var_nm_1L_chr = "tfmn_chr",
                                             evaluate_lgl = F)
                 write_one_predr_mdl_outp(data_tb,
                                          folds_ls = folds_ls,
                                          dep_var_nm_1L_chr  = dep_var_nm_1L_chr , 
                                          tfmn_1L_chr = tfmn_1L_chr,
                                          predr_var_nm_1L_chr = .x, 
                                          predr_var_desc_1L_chr = NA_character_,
                                          predr_vals_dbl = NA_real_,
                                          mdl_type_1L_chr = mdl_type_1L_chr,
                                          path_to_write_to_1L_chr = path_to_write_to_1L_chr,
                                          mdl_types_lup = mdl_types_lup,
                                          mdl_fl_nm_1L_chr = paste0(fl_nm_pfx_1L_chr,
                                                                    "_",
                                                   .x,
                                                   "_MDL"
                                                   ),
                                          plt_idcs_int = c(3,5)) %>%
                   dplyr::select((-Model)) %>%
                   dplyr::mutate(Predictor = .x) %>%
                   dplyr::select(Predictor, dplyr::everything())
               })
  return(smry_of_mdl_sngl_predrs_tb)
  
}
write_mdls_with_covars <- function(data_tb,
                                   predr_var_nm_chr,
                                   mdl_type_1L_chr,
                                   path_to_write_to_1L_chr,
                                   fl_nm_pfx_1L_chr = "CT",
                                   mdl_types_lup = NULL){
      if(is.null(mdl_types_lup))
        mdl_types_lup <- data("mdl_types_lup", package = "FBaqol", envir = environment())
  smry_of_mdls_with_covars_tb <- purrr::map_dfr(predr_var_nm_chr,
                                                ~{
                 mdl <- make_one_predr_mdl(data_tb,
                   predr_var_nm_1L_chr = .x,
                   covar_var_nms_chr = covar_var_nms_chr,
                   tfmn_1L_chr = "NTF",
                   mdl_type_1L_chr = mdl_type_1L_chr,
                   control_1L_chr = NA_character_,
                   mdl_types_lup = mdl_types_lup,
                   start_1L_chr = NA_character_)
                 mdl_fl_nm_1L_chr <- paste0(fl_nm_pfx_1L_chr,"_",.x,
                                            "_",mdl_type_1L_chr)
                 saveRDS(mdl,paste0(path_to_write_to_1L_chr,"/",mdl_fl_nm_1L_chr,".RDS"))
                 
                 tibble::tibble(variable = .x,
                     Rsquare=caret::R2(data_tb %>% dplyr::pull(!!rlang::sym(dep_var_nm_1L_chr)), predict(mdl), form = "traditional"),
                     AIC=AIC(mdl), BIC=BIC(mdl),
                     Significant=paste(names(which(summary(mdl)$coefficients[,4]<0.01)),
                                       collapse = " "))
               })
  saveRDS(smry_of_mdls_with_covars_tb,paste0(path_to_write_to_1L_chr,"/",
                                             paste0(fl_nm_pfx_1L_chr,"_","SMRY",
                                            "_",mdl_type_1L_chr),
                                             ".RDS"))
  return(smry_of_mdls_with_covars_tb)
  
}
write_one_predr_mdl_plts <- function(data_tb, 
                                     mdl,
                                     mdl_type_1L_chr = "OLS_NTF",
                                     dep_var_nm_1L_chr = "aqol6d_total_w",
                                     tfmn_1L_chr = "NTF",
                                     predr_var_nm_1L_chr,
                                     predr_var_desc_1L_chr,
                                     predr_vals_dbl,
                                     path_to_write_to_1L_chr,
                                     pred_type_1L_chr = NULL,
                                     tfmn_for_bnml_1L_lgl = F,
                                     family_1L_chr = NA_character_,
                                     plt_idcs_int = 1:5){
      data_tb <- data_tb %>%
        dplyr::filter(!is.na(!!rlang::sym(predr_var_nm_1L_chr)))
  tfd_data_tb <- transform_data_tb_for_cmprsn(data_tb, 
                                              mdl = mdl, 
                                              pred_type_1L_chr = pred_type_1L_chr,
                                              tfmn_for_bnml_1L_lgl = tfmn_for_bnml_1L_lgl,
                                              family_1L_chr = family_1L_chr) 
  predn_ds_tb <- make_predn_ds_with_one_predr(mdl, 
                                              dep_var_nm_1L_chr = dep_var_nm_1L_chr,
                                              tfmn_1L_chr = tfmn_1L_chr,
                                              predr_var_nm_1L_chr = predr_var_nm_1L_chr, 
                                              predr_vals_dbl = predr_vals_dbl,
                                              pred_type_1L_chr = pred_type_1L_chr)
  purrr::pwalk(list(plt_fn_ls = list(plot_lnr_cmprsn, plot_auto_lm, plot_obsd_predd_dnst, plot_obsd_predd_dnst, plot_sctr_lnr_cmprsn)[plt_idcs_int],
                    fn_args_ls_ls = list(list(data_tb = data_tb,
                                        predn_ds_tb = predn_ds_tb,
                                        predr_var_nm_1L_chr = predr_var_nm_1L_chr,
                                        predr_var_desc_1L_chr = predr_var_desc_1L_chr),
                                      list(mdl,
                                           which_dbl = 1:6, 
                                           ncol_1L_int = 3L,
                                           label_size_1L_int = 3),
                                      list(tfd_data_tb = tfd_data_tb),
                                      list(tfd_data_tb = transform_data_tb_for_cmprsn(data_tb, 
                                                                                      mdl = mdl,
                                                                                      tf_type_1L_chr = ifelse(!4 %in% plt_idcs_int,"Predicted","Simulated"), 
                                                                                      pred_type_1L_chr = NULL, 
                                                                                      tfmn_for_bnml_1L_lgl = tfmn_for_bnml_1L_lgl,
                                                                                      family_1L_chr = family_1L_chr),
                                           predd_val_var_nm_1L_chr = "Simulated"),
                                      list(tfd_data_tb = tfd_data_tb))[plt_idcs_int],
                 plt_nm_sfx_chr = c("_lnr_cmprsn","_auto_plt","_pred_dnsty","_simd_dnsty","_pred_sctr")[plt_idcs_int],
                 size_ls = list(c(6,6),c(4,7),c(6,6),c(6,6),c(6,6))[plt_idcs_int]), 
            ~ write_brm_mdl_plt_fl(plt_fn = ..1,
                     fn_args_ls = ..2,
                     path_to_write_to_1L_chr = path_to_write_to_1L_chr,
                     plt_nm_1L_chr = paste0(mdl_type_1L_chr,
                                            ..3),
                     height_1L_dbl = ..4[1],
                     width_1L_dbl = ..4[2]))
  
}
write_one_predr_mdl_outp <- function(data_tb,
                                     folds_ls,
                                     dep_var_nm_1L_chr = "aqol6d_total_w",
                                     tfmn_1L_chr = "NTF",
                                     predr_var_nm_1L_chr, 
                                     predr_var_desc_1L_chr,
                                     predr_vals_dbl,
                                     mdl_type_1L_chr = "OLS_NTF",
                                     mdl_types_lup = NULL,
                                     path_to_write_to_1L_chr,
                                     mdl_fl_nm_1L_chr,
                                     plt_idcs_int = NA_integer_){
  if(is.null(mdl_types_lup))
    mdl_types_lup <- data("mdl_types_lup", package = "FBaqol", envir = environment())
  data_tb <- data_tb %>%
        dplyr::filter(!is.na(!!rlang::sym(predr_var_nm_1L_chr)))
  arg_vals_chr <- c("control_chr","family_chr","pred_type_chr") %>%
    purrr::map_chr(~ready4fun::get_from_lup_obj(mdl_types_lup,
                                                   match_var_nm_1L_chr = "short_name_chr",
                                                   match_value_xx = mdl_type_1L_chr,
                                                   target_var_nm_1L_chr = .x,
                                                   evaluate_lgl = F))
  control_1L_chr <- arg_vals_chr[1]
  family_1L_chr <- arg_vals_chr[2]
  pred_type_1L_chr <- arg_vals_chr[3]
  if(is.na(pred_type_1L_chr))
    pred_type_1L_chr <- NULL
  if(is.na(plt_idcs_int[1])){
      plt_idcs_int <- 1:5
  if(!is.na(control_1L_chr)){
      if(control_1L_chr %>% startsWith("betareg"))
    plt_idcs_int <- c(1,3,5)
  }
  }
  tfmn_for_bnml_1L_lgl <- ready4fun::get_from_lup_obj(mdl_types_lup,
                                                   match_var_nm_1L_chr = "short_name_chr",
                                                   match_value_xx = mdl_type_1L_chr,
                                                   target_var_nm_1L_chr = "tfmn_for_bnml_lgl",
                                                   evaluate_lgl = F)

  data_tb <- data_tb %>% dplyr::mutate(!!rlang::sym(transform_dep_var_nm(dep_var_nm_1L_chr,
                                                                         tfmn_1L_chr = tfmn_1L_chr)) := !!rlang::sym(dep_var_nm_1L_chr) %>% calculate_dep_var_tfmn())
  mdl <- make_one_predr_mdl(data_tb,
                            dep_var_nm_1L_chr = dep_var_nm_1L_chr,
                            tfmn_1L_chr = tfmn_1L_chr,
                            predr_var_nm_1L_chr = predr_var_nm_1L_chr, 
                            mdl_type_1L_chr = mdl_type_1L_chr,
                            mdl_types_lup = mdl_types_lup,
                            control_1L_chr = control_1L_chr)
  write_one_predr_mdl_plts(data_tb,
                         mdl = mdl,
                         mdl_type_1L_chr = mdl_fl_nm_1L_chr,
                         dep_var_nm_1L_chr = dep_var_nm_1L_chr,
                         tfmn_1L_chr = tfmn_1L_chr,
                         predr_var_nm_1L_chr = predr_var_nm_1L_chr,
                         predr_var_desc_1L_chr = predr_var_desc_1L_chr,
                         predr_vals_dbl = predr_vals_dbl,
                         path_to_write_to_1L_chr = path_to_write_to_1L_chr,
                         pred_type_1L_chr = pred_type_1L_chr,
                         tfmn_for_bnml_1L_lgl = tfmn_for_bnml_1L_lgl,
                         family_1L_chr = family_1L_chr,
                         plt_idcs_int = plt_idcs_int)
  smry_of_one_predr_mdl_tb <- make_smry_of_one_predr_mdl(data_tb,
                                                         mdl = mdl,
                                                         folds_ls = folds_ls,
                                                         dep_var_nm_1L_chr = dep_var_nm_1L_chr,
                                                         tfmn_1L_chr = tfmn_1L_chr,
                                                         predr_var_nm_1L_chr = predr_var_nm_1L_chr,
                                                         mdl_type_1L_chr = mdl_type_1L_chr,
                                                         mdl_types_lup = mdl_types_lup,
                                                         pred_type_1L_chr = pred_type_1L_chr)
  saveRDS(mdl,paste0(path_to_write_to_1L_chr,"/",mdl_fl_nm_1L_chr,".RDS"))
  return(smry_of_one_predr_mdl_tb)
}
write_predr_cmprsn_outps <- function(data_tb,
                                     path_to_write_to_1L_chr,
                                     dep_var_nm_1L_chr = "aqol6d_total_w",
                                     main_predrs_chr,
                                     max_nbr_of_boruta_mdl_runs_int = 300L){
  all_preders_chr <- c(dep_var_nm_1L_chr, main_predrs_chr)
data_tb <- data_tb %>%
dplyr::select(!!!rlang::syms(all_preders_chr)) %>% 
   na.omit()
rf_mdl <- randomForest::randomForest(as.formula(paste0(dep_var_nm_1L_chr," ~ .")), data=data_tb, importance = TRUE)
boruta_mdl <- Boruta::Boruta(as.formula(paste0(dep_var_nm_1L_chr," ~ .")), data = data_tb, maxRuns = max_nbr_of_boruta_mdl_runs_int)
purrr::pwalk(list(fn_ls = list(randomForest::varImpPlot,plot),
                 fn_args_ls_ls = list(list(rf_mdl, 
                                           main = ""),
                                      list(boruta_mdl, 
                                           cex=1.5, 
                                           cex.axis=0.8,#pin=c(6,4),
                                           las=2, 
                                           xlab="", 
                                           main="")),
                plt_nm_sfx_chr = c("_rf_var_imp","_boruta_var_imp"),
                 size_ls = list(c(6,6),c(4,6))),
            ~ write_brm_mdl_plt_fl(plt_fn = ..1,
                     fn_args_ls = ..2,
                     path_to_write_to_1L_chr = path_to_write_to_1L_chr,
                     plt_nm_1L_chr = paste0("pred_cmprsn",
                                            ..3),
                     height_1L_dbl = ..4[1],
                     width_1L_dbl = ..4[2]))
confirmed_predrs_chr <- names(boruta_mdl$finalDecision)[boruta_mdl$finalDecision=="Confirmed"]
confirmed_predrs_tb <- rf_mdl$importance %>% tibble::as_tibble(rownames = "predr_chr") %>%
  dplyr::arrange(dplyr::desc(`%IncMSE`)) %>% 
  dplyr::filter(predr_chr %in% confirmed_predrs_chr)
return(confirmed_predrs_tb)
}
write_sngl_predr_mdls_outps <- function(data_tb,
                                        folds_ls,
                                        mdl_types_chr,
                                        dep_var_nm_1L_chr = "aqol6d_total_w",
                                        predr_var_nm_1L_chr,
                                        predr_var_desc_1L_chr,
                                        predr_vals_dbl,
                                        path_to_write_to_1L_chr,
                                        mdl_types_lup = NULL){
    if(is.null(mdl_types_lup))
      mdl_types_lup <- data("mdl_types_lup", package = "FBaqol", envir = environment())
    data_tb <- data_tb %>%
        dplyr::filter(!is.na(!!rlang::sym(predr_var_nm_1L_chr)))
  smry_of_sngl_predr_mdls_tb <- purrr::map_dfr(mdl_types_chr,
               ~ {
                 tfmn_1L_chr <- ready4fun::get_from_lup_obj(mdl_types_lup, 
                                             match_var_nm_1L_chr = "short_name_chr",
                                             match_value_xx = .x,
                                             target_var_nm_1L_chr = "tfmn_chr",
                                             evaluate_lgl = F)
                 write_one_predr_mdl_outp(data_tb,
                                          folds_ls = folds_ls,
                                          dep_var_nm_1L_chr  = dep_var_nm_1L_chr , 
                                          tfmn_1L_chr = tfmn_1L_chr,
                                          predr_var_nm_1L_chr = predr_var_nm_1L_chr, 
                                          predr_var_desc_1L_chr = predr_var_desc_1L_chr,
                                          predr_vals_dbl = predr_vals_dbl,
                                          mdl_type_1L_chr = .x,
                                          path_to_write_to_1L_chr = path_to_write_to_1L_chr,
                                          mdl_types_lup = mdl_types_lup,
                                          mdl_fl_nm_1L_chr = paste0("RT_",
                                                   predr_var_nm_1L_chr,
                                                   "_",
                                                   .x,
                                                   "_MDL"
                                                   ))
               }) %>%
    dplyr::arrange(dplyr::desc(RsquaredP))
  return(smry_of_sngl_predr_mdls_tb)
  
                                        }
mdl_types_lup <- dplyr::bind_rows(FBaqol::mdl_types_lup,
  tibble::tibble(short_name_chr = c("OLS_NTF",
                                     "OLS_LOG",
                                     "OLS_LOGIT",
                                     "OLS_LOGLOG",
                                     "OLS_CLL",
                                    "GLM_GSN_LOG",
                                    "GLM_BNL_LOG",
                                    "GLM_BNL_LGT",
                                    "GLM_BNL_CLL",
                                    "BET_LOG",
                                    "BET_LGT",
                                    "BET_CLL"),
               long_name_chr = c("Ordinary Least Squares (No transformation)",
                                    "Ordinary Least Squares (Log transformation)",
                                    "Ordinary Least Squares (Logit transformation)",
                                    "Ordinary Least Squares (Log Log transformation)",
                                    "Ordinary Least Squares (Complementary Log Log transformation)",
                                 "Generalised Linear Mixed Model with Gaussian distribution and log link",
                                 "Generalised Linear Mixed Model with Binomial distribution and log link",
                                 "Generalised Linear Mixed Model with Binomial distribution and logit link",
                                 "Generalised Linear Mixed Model with Binomial distribution and complementary log log link", 
                                 "Beta Regression Model with Binomial distribution and log link",
                                 "Beta Regression Model with Binomial distribution and logit link",
                                 "Beta Regression Model with Binomial distribution and complementary log log link"))) %>%
  dplyr::mutate(control_chr = c(rep(NA_character_,11),rep("betareg::betareg.control",3)),
                family_chr = c(rep(NA_character_,7),"gaussian(log)","quasibinomial(log)","quasibinomial(logit)","quasibinomial(cloglog)", rep(NA_character_,3)),
                fn_chr = c(NA_character_,rep("lm",6),rep("glm",4),rep("betareg::betareg",3)),
                start_chr = c(rep(NA_character_,7),
                              rep("-0.1,-0.1",4),
                              rep("-0.5,-0.1,3",3)),
                
                pred_type_chr = c(rep(NA_character_,7),
                                 rep("response",7)),
                tfmn_chr = dplyr::case_when(startsWith(short_name_chr, "OLS_") ~ purrr::map_chr(short_name_chr, ~ {
                  idx_1L_int <- 1 + stringi::stri_locate_last_fixed(.x,"_")[1,1] %>% as.vector()
                  stringr::str_sub(.x, start = idx_1L_int)
                  }),
                                            T ~ "NTF"),
                tfmn_for_bnml_lgl = c(rep(F,8),rep(T,3),rep(F,3)))

```

```{r}
set.seed(12345)
```

```{r}
path_to_write_fls_to_1L_chr <- params$path_to_write_fls_to_1L_chr
dir_nm_1L_chr <- params$dir_nm_1L_chr
path_to_write_to_1L_chr <- paste0(path_to_write_fls_to_1L_chr,
                                                      "/",
                                                      dir_nm_1L_chr)
dep_var_nm_1L_chr <- "aqol6d_total_w"
main_predrs_chr <- c("BADS","GAD7","K6","OASIS","PHQ9","SCARED")
covar_var_nms_chr <- c("d_sex_birth_s", "SOFAS", "c_p_diag_s", "c_clinical_staging_s", "d_age",  "d_sexual_ori_s", "d_country_bir_s", "d_relation_s", "d_studying_working")
n_folds_1L_int <- 10L
round_var_nm_1L_chr <- "round"
round_bl_val_1L_chr <- "Baseline"
prefd_mdl_types_chr <- c("OLS_CLL", "GLM_GSN_LOG")
prefd_covars_chr <- "SOFAS"
```

```{r}
data_tb <- transform_raw_aqol_tb_to_aqol6d_tb(readRDS(params$path_to_data_1L_chr))
bl_tb <- transform_ds_for_tstng(data_tb, dep_var_nm_1L_chr = dep_var_nm_1L_chr, main_predrs_chr = main_predrs_chr, dep_var_max_val_1L_dbl = 0.999, round_val_1L_chr = "Baseline")
```

```{r}
folds_ls <- caret::createFolds(bl_tb %>% dplyr::pull(!!rlang::sym(dep_var_nm_1L_chr)) , 
                                 k = n_folds_1L_int, 
                                 list = TRUE, 
                                 returnTrain = FALSE)
```

```{r}
 bc_plt_path_1L_chr <- write_box_cox_tfmn(data_tb = bl_tb, 
                    predr_var_nm_1L_chr = "PHQ9", 
                    path_to_write_to_1L_chr = path_to_write_to_1L_chr, 
                    mdl_types_lup = mdl_types_lup) 
```

```{r}
smry_of_sngl_predr_mdls_tb <- write_sngl_predr_mdls_outps(data_tb = bl_tb,
                                                          folds_ls = folds_ls,
                                                          mdl_types_chr = c("OLS_NTF","OLS_LOG", "OLS_LOGIT", "OLS_LOGLOG", "OLS_CLL", "GLM_GSN_LOG", "GLM_BNL_LOG", "GLM_BNL_LGT", "GLM_BNL_CLL", "BET_LOG","BET_LGT", "BET_CLL"),
                                                          dep_var_nm_1L_chr = "aqol6d_total_w",
                                                          predr_var_nm_1L_chr = "PHQ9",
                                                          predr_var_desc_1L_chr = "PHQ9 total score",
                                                          predr_vals_dbl = 0:27, 
                                                          path_to_write_to_1L_chr = path_to_write_to_1L_chr,
                                                          mdl_types_lup = mdl_types_lup)
```

```{r}
predr_cmprsns_tb <- write_predr_cmprsn_outps(data_tb = bl_tb,
                                             path_to_write_to_1L_chr = path_to_write_to_1L_chr,
                                             dep_var_nm_1L_chr = "aqol6d_total_w",
                                             main_predrs_chr,
                                             max_nbr_of_boruta_mdl_runs_int = 300L)

```

## Individual predictors

```{r}
smry_of_mdl_sngl_predrs_tb <- write_mdl_sngl_predrs_outps(data_tb = bl_tb,
                            folds_ls = folds_ls,
                            predr_var_nm_chr = predr_cmprsns_tb$predr_chr,
                            mdl_type_1L_chr = "GLM_GSN_LOG",
                            dep_var_nm_1L_chr = "aqol6d_total_w",
                            path_to_write_to_1L_chr = path_to_write_to_1L_chr,
                            mdl_types_lup = mdl_types_lup)
```

## Additional confounding variables

```{r}
bl_tb <- data_tb %>% transform_ds_for_tstng(main_predrs_chr = main_predrs_chr, 
                                   covar_var_nms_chr = covar_var_nms_chr,
                                   remove_all_mssng_1L_lgl = T,
                                   round_val_1L_chr = "Baseline")
mdls_with_covars_smry_tb <- write_mdls_with_covars(bl_tb,
                       predr_var_nm_chr = predr_var_nm_chr,
                       mdl_type_1L_chr = prefd_mdl_types_chr[2],
                       path_to_write_to_1L_chr = path_to_write_to_1L_chr,
                       fl_nm_pfx_1L_chr = "CT",
                       mdl_types_lup = mdl_types_lup)

signt_covars_chr <- get_significant_covars(mdls_with_covars_smry_tb = mdls_with_covars_smry_tb,
                       covar_var_nms_chr)
if(is.na(prefd_covars_chr))
  prefd_covars_chr <- signt_covars_chr

```


## Checking 

### PHQ9 
```{r}
baseline<-Baseline_follow[Baseline_follow$round=="Baseline",] %>% 
   dplyr::select(aqol6d_total_w ,PHQ9, SOFAS) %>% 
   na.omit()

fit = glm(aqol6d_total_w ~ PHQ9 + SOFAS  , data = baseline,family=gaussian(log))

summary(fit)
baseline %>% 
    mutate(Predicted=simulate(fit)$sim_1, 
         Original=aqol6d_total_w) %>% 
    gather(variable, value, Predicted, Original) %>%
    ggplot(aes(x = value, fill = variable)) +
    geom_bkde(alpha=0.5) +
    geom_rug() +
    scale_fill_viridis( discrete = TRUE) +
    theme_bw() +
    theme(legend.position="bottom") +
    labs( x="AQoL-6D utility score",fill="") 

baseline %>% 
     mutate(Predicted=predict(fit,type="response"),  
         Original=aqol6d_total_w) %>% 
  ggplot(aes(x = Original, y=Predicted)) +
  geom_point() + 
  geom_smooth(method = "loess", size = 1.5) +
  theme_bw() +
  geom_abline(intercept = 0, slope = 1, color="red", 
                 linetype="dashed", size=1.5) +
  xlim(0, 1) + ylim(0, 1) 


```


### BADS 
```{r}
baseline<-Baseline_follow[Baseline_follow$round=="Baseline",] %>% 
   dplyr::select(aqol6d_total_w ,BADS, SOFAS) %>% 
   na.omit()

fit = glm(aqol6d_total_w ~ BADS + SOFAS  , data = baseline,family=gaussian(log))

summary(fit)
baseline %>% 
    mutate(Predicted=simulate(fit)$sim_1, 
         Original=aqol6d_total_w) %>% 
    gather(variable, value, Predicted, Original) %>%
    ggplot(aes(x = value, fill = variable)) +
    geom_bkde(alpha=0.5) +
    geom_rug() +
    scale_fill_viridis( discrete = TRUE) +
    theme_bw() +
    theme(legend.position="bottom") +
    labs( x="AQoL-6D utility score",fill="") 

baseline %>% 
     mutate(Predicted=predict(fit,type="response"),  
         Original=aqol6d_total_w) %>% 
  ggplot(aes(x = Original, y=Predicted)) +
  geom_point() + 
  geom_smooth(method = "loess", size = 1.5) +
  theme_bw() +
  geom_abline(intercept = 0, slope = 1, color="red", 
                 linetype="dashed", size=1.5) +
  xlim(0, 1) + ylim(0, 1) 


```



### GAD7 
```{r}
baseline<-Baseline_follow[Baseline_follow$round=="Baseline",] %>% 
   dplyr::select(aqol6d_total_w ,GAD7, SOFAS) %>% 
   na.omit()

fit = glm(aqol6d_total_w ~ GAD7 + SOFAS  , data = baseline,family=gaussian(log))

summary(fit)
baseline %>% 
    mutate(Predicted=simulate(fit)$sim_1, 
         Original=aqol6d_total_w) %>% 
    gather(variable, value, Predicted, Original) %>%
    ggplot(aes(x = value, fill = variable)) +
    geom_bkde(alpha=0.5) +
    geom_rug() +
    scale_fill_viridis( discrete = TRUE) +
    theme_bw() +
    theme(legend.position="bottom") +
    labs( x="AQoL-6D utility score",fill="") 

baseline %>% 
     mutate(Predicted=predict(fit,type="response"),  
         Original=aqol6d_total_w) %>% 
  ggplot(aes(x = Original, y=Predicted)) +
  geom_point() + 
  geom_smooth(method = "loess", size = 1.5) +
  theme_bw() +
  geom_abline(intercept = 0, slope = 1, color="red", 
                 linetype="dashed", size=1.5) +
  xlim(0, 1) + ylim(0, 1) 


```


### OASIS  
```{r}
baseline<-Baseline_follow[Baseline_follow$round=="Baseline",] %>% 
   dplyr::select(aqol6d_total_w ,OASIS, SOFAS) %>% 
   na.omit()

fit = glm(aqol6d_total_w ~ OASIS + SOFAS  , data = baseline,family=gaussian(log))

summary(fit)
baseline %>% 
    mutate(Predicted=simulate(fit)$sim_1, 
         Original=aqol6d_total_w) %>% 
    gather(variable, value, Predicted, Original) %>%
    ggplot(aes(x = value, fill = variable)) +
    geom_bkde(alpha=0.5) +
    geom_rug() +
    scale_fill_viridis( discrete = TRUE) +
    theme_bw() +
    theme(legend.position="bottom") +
    labs( x="AQoL-6D utility score",fill="") 

baseline %>% 
     mutate(Predicted=predict(fit,type="response"),  
         Original=aqol6d_total_w) %>% 
  ggplot(aes(x = Original, y=Predicted)) +
  geom_point() + 
  geom_smooth(method = "loess", size = 1.5) +
  theme_bw() +
  geom_abline(intercept = 0, slope = 1, color="red", 
                 linetype="dashed", size=1.5) +
  xlim(0, 1) + ylim(0, 1) 


```



### SCARED 
```{r}
baseline<-Baseline_follow[Baseline_follow$round=="Baseline",] %>% 
   dplyr::select(aqol6d_total_w ,SCARED, SOFAS) %>% 
   na.omit()

fit = glm(aqol6d_total_w ~ SCARED + SOFAS  , data = baseline,family=gaussian(log))

summary(fit)
baseline %>% 
    mutate(Predicted=simulate(fit)$sim_1, 
         Original=aqol6d_total_w) %>% 
    gather(variable, value, Predicted, Original) %>%
    ggplot(aes(x = value, fill = variable)) +
    geom_bkde(alpha=0.5) +
    geom_rug() +
    scale_fill_viridis( discrete = TRUE) +
    theme_bw() +
    theme(legend.position="bottom") +
    labs( x="AQoL-6D utility score",fill="") 

baseline %>% 
     mutate(Predicted=predict(fit,type="response"),  
         Original=aqol6d_total_w) %>% 
  ggplot(aes(x = Original, y=Predicted)) +
  geom_point() + 
  geom_smooth(method = "loess", size = 1.5) +
  theme_bw() +
  geom_abline(intercept = 0, slope = 1, color="red", 
                 linetype="dashed", size=1.5) +
  xlim(0, 1) + ylim(0, 1) 


```



### K6 
```{r}
baseline<-Baseline_follow[Baseline_follow$round=="Baseline",] %>% 
   dplyr::select(aqol6d_total_w ,K6, SOFAS) %>% 
   na.omit()

fit = glm(aqol6d_total_w ~ K6 + SOFAS  , data = baseline,family=gaussian(log))

summary(fit)
baseline %>% 
    mutate(Predicted=simulate(fit)$sim_1, 
         Original=aqol6d_total_w) %>% 
    gather(variable, value, Predicted, Original) %>%
    ggplot(aes(x = value, fill = variable)) +
    geom_bkde(alpha=0.5) +
    geom_rug() +
    scale_fill_viridis( discrete = TRUE) +
    theme_bw() +
    theme(legend.position="bottom") +
    labs( x="AQoL-6D utility score",fill="") 

baseline %>% 
     mutate(Predicted=predict(fit,type="response"),  
         Original=aqol6d_total_w) %>% 
  ggplot(aes(x = Original, y=Predicted)) +
  geom_point() + 
  geom_smooth(method = "loess", size = 1.5) +
  theme_bw() +
  geom_abline(intercept = 0, slope = 1, color="red", 
                 linetype="dashed", size=1.5) +
  xlim(0, 1) + ylim(0, 1) 


```
