---
title: "AQoL 6D Preferred Models"
author: "Matthew Hamilton & Caroline Gao"
date: "21/10/2020"
output: html_document
---


## Functions 
```{r}
calculate_rmse <- function(y_dbl,yhat_dbl){
  rmse_dbl <- sqrt(mean((yhat_dbl-y_dbl)^2))
  return(rmse_dbl)
  }
calculate_rmse_tfmn <- function(y_dbl,yhat_dbl){
  rmse_tfmn_dbl <- sqrt(mean((1-exp(-exp(yhat_dbl))-y_dbl)^2))
  return(rmse_tfmn_dbl)
}
fit_clg_log_tfmn <- function(data_tb,
                             dep_var_nm_1L_chr = "aqol6d_total_w_cloglog",
                             predictor_vars_nms_chr,
                             id_var_nm_1L_chr = "fkClientID",
                             iters_1L_int = 4000L,
                             seed_1L_int = 1000L
                           ){
  mdl_ls <- fit_ts_model_with_brm(data_tb,
                                        dep_var_nm_1L_chr = dep_var_nm_1L_chr,
                                        predictor_vars_nms_chr = predictor_vars_nms_chr,
                                        link_1L_chr = "identity",
                                        id_var_nm_1L_chr = id_var_nm_1L_chr,
                                        iters_1L_int = iters_1L_int,
                                        seed_1L_int = seed_1L_int)
    return(mdl_ls)
}
fit_gsn_log_lnk <- function(data_tb,
                            dep_var_nm_1L_chr = "aqol6d_total_w",
                            predictor_vars_nms_chr,
                            id_var_nm_1L_chr = "fkClientID",
                            iters_1L_int = 4000L,
                            seed_1L_int = 1000L){
  mdl_ls <- fit_ts_model_with_brm(data_tb,
                                        dep_var_nm_1L_chr = dep_var_nm_1L_chr,
                                        predictor_vars_nms_chr = predictor_vars_nms_chr,
                                        link_1L_chr = "log",
                                        id_var_nm_1L_chr = id_var_nm_1L_chr,
                                        iters_1L_int = iters_1L_int,
                                        seed_1L_int = seed_1L_int)
  return(mdl_ls)
}
fit_ts_model_with_brm <- function(data_tb,
                               dep_var_nm_1L_chr,
                               predictor_vars_nms_chr,
                               id_var_nm_1L_chr,
                               link_1L_chr = "identity",
                               iters_1L_int = 4000L,
                               seed_1L_int = 1000L){
      mdl_ls <- brms::brm(formula = as.formula(paste0(dep_var_nm_1L_chr,#"aqol6d_total_w_cloglog",
                                                            " ~ ", 
                                                        purrr::map_chr(predictor_vars_nms_chr,
                                                                       ~ paste0(.x,
                                                                                "_baseline + ",
                                                                                .x,"_change + ")) %>%
                                                          paste0(collapse = ""),
                                                        "(1|",
                                                        id_var_nm_1L_chr,
                                                        ")")), 
                                data = data_tb,
                                family = gaussian(link=link_1L_chr), 
                                iter = iters_1L_int,
                                seed = seed_1L_int)
      return(mdl_ls)
}
make_smry_of_brm_mdl <- function(mdl_ls,
                                 data_tb,
                                 dep_var_nm_1L_chr = "aqol6d_total_w",
                                 predictor_vars_nms_chr,
                                 fn = calculate_rmse,
                                 mdl_nm_1L_chr = NA_character_,
                                 seed_1L_dbl = 23456){
  if(is.na(mdl_nm_1L_chr))
    mdl_nm_1L_chr <- predictor_vars_nms_chr[1]
  set.seed(seed_1L_dbl)
  predictions <- predict(mdl_ls, summary=F)
  coef <- summary(mdl_ls, digits = 4)$fixed
  coef <- coef[1:nrow(coef),1:4]
  R2 <- brms::bayes_R2(mdl_ls)
  RMSE <- psych::describe(apply(predictions,
                                1,
                                fn,
                                y_dbl = data_tb %>% dplyr::pull(!!rlang::sym(dep_var_nm_1L_chr))),
                          quant = c(.25, .75), 
                          skew = F, 
                          ranges = F)
  RMSE <- cbind(RMSE$mean, RMSE$sd, RMSE$Q0.25, RMSE$Q0.75)
  Sigma <- summary(mdl_ls, digits = 4)$spec_par[1:4]
  smry_of_brm_mdl_tb <- data.frame(round(rbind(coef,R2,RMSE,Sigma),3))  %>% 
    dplyr::mutate(Parameter=c("Intercept",purrr::map(predictor_vars_nms_chr,
                                  ~ paste0(.x, c(" baseline", 
                                                 " change"))) %>%
                         purrr::flatten_chr(),
                       "R2", "RMSE", "Sigma"),
           Model = mdl_nm_1L_chr) %>% 
    dplyr::mutate(`95% CI`= paste(`l.95..CI`,",", `u.95..CI`)) %>% 
    dplyr::rename (SE=Est.Error) %>% 
    dplyr::select(Model, Parameter, Estimate, SE, `95% CI`)
  return(smry_of_brm_mdl_tb)
}
make_smry_of_ts_mdl <- function(data_tb,
                                          fn,
                                          predictor_vars_nms_chr,
                                          mdl_nm_1L_chr,
                                          path_to_write_to_1L_chr = NA_character_,
                                          dep_var_nm_1L_chr = "aqol6d_total_w",
                                          id_var_nm_1L_chr = "fkClientID",
                                          round_var_nm_1L_chr = "round",
                                          round_bl_val_1L_chr = "Baseline",
                                          iters_1L_int = 4000L,
                                          seed_1L_int = 1000L#,print_plots_1L_lgl = T
                                ){
    tfd_data_tb <- transform_tb_to_mdl_inp(data_tb,
                                     dep_var_nm_1L_chr = dep_var_nm_1L_chr,
                                     predictor_vars_nms_chr = predictor_vars_nms_chr,
                                     id_var_nm_1L_chr = id_var_nm_1L_chr,
                                     round_var_nm_1L_chr = round_var_nm_1L_chr,
                                     round_bl_val_1L_chr = round_bl_val_1L_chr)
    tfd_dep_var_nm_1L_chr <- ifelse(identical(fn,fit_clg_log_tfmn),
                                transform_dep_var_nm_for_cll(dep_var_nm_1L_chr),      
                                dep_var_nm_1L_chr)
    args_ls <- list(data_tb = tfd_data_tb,
                    dep_var_nm_1L_chr = tfd_dep_var_nm_1L_chr, 
                    predictor_vars_nms_chr = predictor_vars_nms_chr,
                    iters_1L_int = iters_1L_int,
                    seed_1L_int = seed_1L_int)
  mdl_ls <- rlang::exec(fn,!!!args_ls)
  smry_of_ts_mdl_ls <- list(smry_of_ts_mdl_tb = make_smry_of_brm_mdl(mdl_ls,
                                            data_tb = tfd_data_tb,
                                            dep_var_nm_1L_chr = tfd_dep_var_nm_1L_chr,
                                            predictor_vars_nms_chr = predictor_vars_nms_chr,
                                            fn = ifelse(identical(fn,fit_gsn_log_lnk),
                                                        calculate_rmse,
                                                        calculate_rmse_tfmn), 
                                            mdl_nm_1L_chr = mdl_nm_1L_chr
                                            ))
  if(!is.na(path_to_write_to_1L_chr)){
    smry_of_ts_mdl_ls$path_to_mdl_ls_1L_chr <- paste0(path_to_write_to_1L_chr,"/",mdl_nm_1L_chr,".RDS")
    saveRDS(mdl_ls,path_to_mdl_ls_1L_chr)
    smry_of_ts_mdl_ls$paths_to_mdl_plts_chr <- write_brm_model_plts(mdl_ls,
                                     tfd_data_tb,
                                     dep_var_nm_1L_chr = dep_var_nm_1L_chr, 
                                     mdl_nm_1L_chr = mdl_nm_1L_chr,
                                     path_to_write_to_1L_chr = path_to_write_to_1L_chr,
                                     round_var_nm_1L_chr = round_var_nm_1L_chr,
                                     tfmn_fn = ifelse(identical(fn, fit_gsn_log_lnk),
                                                      function(x){x},
                                                      function(x){1-exp(-exp(x))}))
  }
return(smry_of_ts_mdl_ls)
}
plot_obsd_predd_dnst <- function(tfd_data_tb){
  tfd_data_tb %>%
    dplyr::mutate(Observed=aqol6d_total_w) %>% 
    tidyr::gather(variable, value, Predicted, Observed) %>%
  ggplot2::ggplot(ggplot2::aes(x = value, fill = variable)) +
    ggalt::geom_bkde(alpha = 0.5) +
    ggplot2::geom_rug() +
    viridis::scale_fill_viridis(discrete = TRUE) +
    ggplot2::theme_bw() + 
    ggplot2::theme(legend.position="bottom") +
    ggplot2::labs( x="AQoL-6D utility score",y="Density", fill="")
}
plot_obsd_predd_sctr <- function(tfd_data_tb, 
                                        dep_var_nm_1L_chr, 
                                        dep_var_desc_1L_chr,
                                        args_ls){
  ggplot2::ggplot(tfd_data_tb) +
                       rlang::exec(ggplot2::geom_point,
                                   ggplot2::aes(x = !!rlang::sym(dep_var_nm_1L_chr), 
                                                y = Predicted,
                                                col = !!rlang::sym(round_var_nm_1L_chr)),
                                   size = 1,
                                   !!!args_ls) + 
                       ggplot2::theme_bw()  + 
                       ggplot2::xlim(0,1)  + 
                       ggplot2::ylim(0,1)  + 
                       ggplot2::scale_color_manual(values=c("#D55E00","#56B4E9"))  +
                       ggplot2::labs(x = paste0("Observed ", dep_var_desc_1L_chr),
                                     y = paste0("Predicted ", dep_var_desc_1L_chr), 
                                     col = "") +
                       ggplot2::theme(legend.position="bottom")
                     }

predict_from_mdl_coefs <- function(smry_of_mdl_tb,
                                   new_data_tb){
  coef_tb <- smry_of_mdl_tb %>% dplyr::filter(!Parameter %in% c("R2", "RMSE", "Sigma"))
  vecs_1_ls <- coef_tb$Parameter[-1] %>% 
  purrr::map(~ new_data_tb %>% 
               dplyr::pull(.x %>% stringr::str_replace(" ","_")) * coef_tb %>%
               dplyr::filter(Parameter == .x) %>%
               dplyr::pull(Estimate)
             ) 
  pred_dbl <- exp(Reduce(`+`, vecs_1_ls) + coef_tb %>%
               dplyr::filter(Parameter == "Intercept") %>%
               dplyr::pull(Estimate))
return(pred_dbl)
}
# print_brm_model <- function(mdl_ls,
#                             brm_model_plts_ls,
#                             mdl_nm_1L_chr){
#   cat('\n') 
#   cat("### ", mdl_nm_1L_chr, "\n")
#   cat('\n') 
#   print(brm_model_plts_ls[[1]])
#   #print(summary(mdl_ls, digits = 4))
#   print(brm_model_plts_ls[[2]])
#   print(brm_model_plts_ls[[3]])
#   cat('\n')
# }
transform_tb_to_mdl_inp <- function(data_tb,
                                    dep_var_nm_1L_chr = "aqol6d_total_w",
                                    predictor_vars_nms_chr,
                                    id_var_nm_1L_chr = "fkClientID",
                                    round_var_nm_1L_chr = "round",
                                    round_bl_val_1L_chr = "Baseline"){
    data_tb <- data.frame(data_tb)
  tfd_for_gsn_log_mdl_tb <- data_tb %>% 
    dplyr::select(dplyr::all_of(dep_var_nm_1L_chr),
                  dplyr::all_of(id_var_nm_1L_chr),
                  dplyr::all_of(round_var_nm_1L_chr),
                  dplyr::all_of(predictor_vars_nms_chr)) %>% 
    dplyr::group_by(!!rlang::sym(id_var_nm_1L_chr)) %>% 
    dplyr::arrange(!!rlang::sym(id_var_nm_1L_chr),!!rlang::sym(round_var_nm_1L_chr)) 
  tfd_for_gsn_log_mdl_tb <- tfd_for_gsn_log_mdl_tb %>% 
    dplyr::mutate(dplyr::across(dplyr::all_of(predictor_vars_nms_chr), 
                                .fns = list(baseline = ~ dplyr::first(.)/100,
                                            change = ~ ifelse(round == "Baseline",
                                                              0,
                                                              (.-dplyr::lag(.))/100))))  %>% 
    dplyr::mutate(!!rlang::sym(transform_dep_var_nm_for_cll(dep_var_nm_1L_chr)) := log(-log(1-ifelse(!!rlang::sym(dep_var_nm_1L_chr)==1,0.999,!!rlang::sym(dep_var_nm_1L_chr))))) %>% 
    na.omit()
  return(tfd_for_gsn_log_mdl_tb)
}
transform_dep_var_nm_for_cll <- function(dep_var_nm_1L_chr){
  tfd_dep_var_nm_1L_chr <- paste0(dep_var_nm_1L_chr,"_cloglog")
  return(tfd_dep_var_nm_1L_chr)
}
transform_ts_mdl_data <- function(mdl_ls,
                      data_tb,
                      dep_var_nm_1L_chr = "aqol6d_total_w",
                      predictor_vars_nms_chr,
                      id_var_nm_1L_chr = "fkClientID",
                      mdl_nm_1L_chr#,
                      #path_to_write_to_1L_chr
                      ){
  old_data_tb <- data_tb %>%
          dplyr::select(c(dplyr::all_of(id_var_nm_1L_chr),
                          dplyr::all_of(dep_var_nm_1L_chr),
                          predictor_vars_nms_chr %>% purrr::map(~paste0(.x,
                                                                        c("","_baseline","_change"))) %>%
                            purrr::flatten_chr()))
  cnfdl_mdl_ls <- mdl_ls 
  cnfdl_mdl_ls$data <- old_data_tb %>% as.data.frame() %>%
    dplyr::summarise(dplyr::across(dplyr::everything(), ~ sample(.x,1))) 
#saveRDS(cnfdl_mdl_ls,paste0(path_to_write_to_1L_chr,"/",mdl_nm_1L_chr,".RDS"))
return(cnfdl_mdl_ls)
}
write_brm_model_plts <- function(mdl_ls,
                           tfd_data_tb,
                           mdl_nm_1L_chr,
                           path_to_write_to_1L_chr,
                           dep_var_nm_1L_chr = "aqol6d_total_w",
                           dep_var_desc_1L_chr = "AQoL-6D utility score",
                           round_var_nm_1L_chr = "round",
                           tfmn_fn = function(x){x},
                           units_1L_chr = "in",
                           height_dbl = c(rep(6,2),rep(5,2)), 
                           width_dbl = c(rep(6,2),rep(6,2)),
                           rsl_dbl = rep(300,4),
                           args_ls = NULL,
                           seed_1L_dbl = 23456){
  set.seed(seed_1L_dbl)
  tfd_data_tb$Predicted <- predict(mdl_ls)[,1] %>% tfmn_fn()
   plt_nms_chr <- paste0(mdl_nm_1L_chr, "_", c("coefs","hetg", "dnst","sctr_plt"))
  mdl_plts_paths_ls <- purrr::map(1:4, 
              ~  {
                if(.x %in% c(1,2)){
                  plt_fn <- function(mdl_ls, idx_1L_int){plot(mdl_ls, ask=F, plot = F)[idx_1L_int]}
                  fn_args_ls <- list(mdl_ls = mdl_ls,
                                     idx_1L_int = as.integer(.x))
                }else{
                  if(.x == 3){
                     plt_fn <- plot_obsd_predd_dnst
                     fn_args_ls <- list(tfd_data_tb = tfd_data_tb)
                  }else{
                     plt_fn <- plot_obsd_predd_sctr
                     fn_args_ls <- list(tfd_data_tb = tfd_data_tb, 
                                        dep_var_nm_1L_chr = dep_var_nm_1L_chr, 
                                        dep_var_desc_1L_chr = dep_var_desc_1L_chr,
                                        #plot_fn = sctr_plt_fn,
                                        args_ls = args_ls)
                  }
                }
                write_brm_mdl_plt_fl(plt_fn,
                                   fn_args_ls = fn_args_ls,
                                   path_to_write_to_1L_chr = path_to_write_to_1L_chr,
                                   plt_nm_1L_chr = plt_nms_chr[.x],
                                   units_1L_chr = units_1L_chr, 
                                   width_1L_dbl =  width_dbl[.x], 
                                   height_1L_dbl = height_dbl[.x], 
                                   rsl_1L_dbl = rsl_dbl[.x])
                }) %>%
    stats::setNames(plt_nms_chr)
return(mdl_plts_paths_ls)
}
  write_brm_mdl_plt_fl <- function(plt_fn,
                                   
                                 fn_args_ls = NULL,
                                 path_to_write_to_1L_chr,
                                 plt_nm_1L_chr,
                                 grpx_fn = grDevices::png,
                                 units_1L_chr = "in", 
                                 width_1L_dbl = 6, 
                                 height_1L_dbl = 6, 
                                 rsl_1L_dbl = 300){
    path_to_plot_1L_chr <- paste0(path_to_write_to_1L_chr,
                                  "/",
                                  plt_nm_1L_chr,
                                  ifelse(identical(grpx_fn,grDevices::png),".png",".tiff"))           
    rlang::exec(grpx_fn,
                !!!list(path_to_plot_1L_chr, 
                    units = units_1L_chr, 
                    width = width_1L_dbl, 
                    height = height_1L_dbl, 
                    res = rsl_1L_dbl))
    plt <- rlang::exec(plt_fn,!!!fn_args_ls)
    print(plt)
    dev.off()
    return(path_to_plot_1L_chr)
  }
```

```{r}
# smry_of_gsn_log_mdl_1 <- write_and_make_smry_of_ts_mdl(data_tb = Baseline_follow,
#                                                        fn = fit_gsn_log_lnk,
#                                                        predictor_vars_nms_chr = c("PHQ9","SOFAS"),
#                                                        mdl_nm_1L_chr = "PHQ9_GSN_LOG",
#                                                        path_to_data_dir_1L_chr = "../../../../../../../Data/R_Format/Utility_Models",
#                                                        iters_1L_int = 4000L,
#                                                        seed_1L_int = 1000L)
# # new_data_tb <- tibble::tibble(PHQ9_baseline = c(0.14,0.25,0.15,0.2,0.11),
# #                                  PHQ9_change = c(-0.1,-0.05,0.05,-0.06,0.1),
# #                                  SOFAS_baseline = c(0.71,0.69,0.75,0.43,0.29),
# #                                  SOFAS_change = c(0.25,-0.19,0.1,-0.1,0.2))
# 
# new_data_tb <- Baseline_follow
# #path_to_data_dir_1L_chr <- "../../../../../../../Data/R_Format/Utility_Models"
# #mdl_nm_1L_chr <- "PHQ9_GSN_LOG"
# # pred_1_tb <- predict(readRDS(paste0(path_to_data_dir_1L_chr,"/",mdl_nm_1L_chr,".RDS")),
# #         newdata = new_data_tb,
# #         re_formula = NA)
# # pred_1_dbl <- pred_1_tb[,1]
# pred_2_dbl <- predict_from_mdl_coefs(smry_of_gsn_log_mdl_1,
#                        new_data_tb = new_data_tb %>% transform_tb_to_mdl_inp(predictor_vars_nms_chr = c("PHQ9","SOFAS")))
 
```

```{r}
# smry_of_clg_log_tfmn_mdl_1 <- write_and_make_smry_of_ts_mdl(data_tb = Baseline_follow,
#                                                        fn = fit_clg_log_tfmn,
#                                                        predictor_vars_nms_chr = c("PHQ9","SOFAS"),
#                                                        mdl_nm_1L_chr = "PHQ9_CLL_TFN",
#                                                        path_to_data_dir_1L_chr = "../../../../../../../Data/R_Format/Utility_Models",
#                                                        iters_1L_int = 4000L,
#                                                        seed_1L_int = 1000L)

```

