#' ready4u: Map Measures Routinely Collected in Mental Health
#' Services to Health Utility
#'
#' Tools for developping Transfer To Utility (TTU)
#' mapping algorithms to predict health utility from measures routinely
#' collected in mental health services.  This development version of the
#' ready4u package has been made available as part of the process of
#' testing and documenting the package. The tools contained in this
#' development release automate a number of tasks which MODIFY THE
#' DIRECTORY STRUCTURE OF YOUR LOCAL MACHINE.  Therefore you should only
#' trial this software if you feel confident that you understand what it
#' does and have created a sandpit area in which you can safely undertake
#' testing. If you have any questions, please contact the authors
#' (matthew.hamilton@orygen.org.au).  The documentation for this package
#' has been automatically generated by the ready4fun package and is
#' therefore quite rudimentary. Human authored documentation will follow
#' in 2021.
#'
#' To learn more about ready4u, start with the vignettes:
#' `browseVignettes(package = "ready4u")`
#'
"_PACKAGE"
