#' TTU: Transfer to Utility Mapping Algorithm Toolkit
#'
#' Tools for developping Transfer To Utility (TTU) mapping
#' algorithms to predict health utility from other health measures.  This
#' development version of the TTU package has been made available as part
#' of the process of testing and documenting the package.  Some of the
#' documentation for this package has been automatically generated by the
#' ready4fun package and is therefore quite rudimentary. Human edits to
#' improve the quality of documentation will follow in 2021.  If you have
#' any questions, please contact the authors
#' (matthew.hamilton@orygen.org.au).
#'
#' To learn more about TTU, start with the vignettes:
#' `browseVignettes(package = "TTU")`
#'
"_PACKAGE"
