---
output: 
  bookdown::pdf_document2: 
    includes:
      in_header: preamble.tex
    pandoc_args: 
      - "--metadata-file=Header/header_common.yaml"
      - '--lua-filter=Filters/scholarly-metadata.lua'
      - '--lua-filter=Filters/author-info-blocks.lua'
    toc: no
  bookdown::pdf_book: 
    includes:
      in_header: preamble.tex
    pandoc_args: 
      - "--metadata-file=Header/header_common.yaml"
      - '--lua-filter=Filters/scholarly-metadata.lua'
      - '--lua-filter=Filters/author-info-blocks.lua'
  bookdown::html_document2:
    pandoc_args: 
      - "--metadata-file=Header/header_common.yaml"
      - '--lua-filter=Filters/scholarly-metadata.lua'
      - '--lua-filter=Filters/author-info-blocks.lua' 
    toc: yes
  bookdown::markdown_document2:
    base_format: "officedown::rdocx_document"
    number_sections: yes
    toc: yes
    tables:
      style: Table
      layout: autofit
      width: 1.0
      caption:
        style: Table Caption
        pre: 'Table '
        sep: ': '
      conditional:
        first_row: true
        first_column: false
        last_row: false
        last_column: false
        no_hband: false
        no_vband: true
    pandoc_args: 
      - "--metadata-file=Header/header_common.yaml"
      - '--lua-filter=Filters/scholarly-metadata.lua'
      - '--lua-filter=Filters/author-info-blocks.lua'
      - '--lua-filter=Filters/pagebreaks.lua'
params:
  abstract_args_ls: !r NULL
  append_params_ls: !r NULL
  eval_1L_lgl: !r FALSE
  ds_tb: !r NULL
  dv_mdl_desc_1L_chr: !r NA_character_ #
  header_yaml_args_ls: !r NULL
  inc_fl_types_chr: ".pdf" #
  output_type_1L_chr: "PDF"
  nbr_of_digits_1L_int: !r 2L
  path_from_top_level_1L_chr: !r NULL
  path_to_data_from_top_level_chr: !r NULL
  purge_data_1L_lgl: FALSE #
  rprt_lup: !r NULL
  rprt_nm_1L_chr: !r NA_character_
  rprt_output_type_1L_chr: "PDF"
  rprt_subtitle_1L_chr: !r NA_character_
  rprt_type_1L_chr: "Report"
  share_mdls_1L_lgl: TRUE #
  subtitle_1L_chr: !r NA_character_
  transform_paths_ls: !r NULL
  use_fake_data_1L_lgl: FALSE
date: "`r format.Date(Sys.Date(),'%B %d, %Y')`"
subtitle: "`r params$subtitle_1L_chr`"
---

# Set up workspace
```{r, child=c('_Set_Up_WS.Rmd')}
```

```{r, child=c('_Get_Outp_Smry.Rmd')}
```

# Create shareable assets
```{r echo=FALSE}
if(params_ls$share_mdls_1L_lgl){
  child_chr <- c('_Write_Shareable_Data.Rmd')
}else{
  child_chr <- NULL
}
```
```{r, child = child_chr[1]}
```
```{r, child=c('_Write_Report.Rmd')}
```

